// This file is auto-generated by @hey-api/openapi-ts

import * as Schema from 'effect/Schema';
import { Multipart } from 'effect/unstable/http';

import type { ModelWithCircularReference } from './types.gen';

/**
 * Model with number-only name
 */
export const _400Schema = Schema.String.annotate({ description: 'Model with number-only name' });

/**
 * Testing multiline comments in string: First line
 * Second line
 *
 * Fourth line
 */
export const CamelCaseCommentWithBreaksSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'Testing multiline comments in string: First line\nSecond line\n\nFourth line' });

/**
 * Testing multiline comments in string: First line
 * Second line
 *
 * Fourth line
 */
export const CommentWithBreaksSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'Testing multiline comments in string: First line\nSecond line\n\nFourth line' });

/**
 * Testing backticks in string: `backticks` and ```multiple backticks``` should work
 */
export const CommentWithBackticksSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'Testing backticks in string: `backticks` and ```multiple backticks``` should work' });

/**
 * Testing backticks and quotes in string: `backticks`, 'quotes', "double quotes" and ```multiple backticks``` should work
 */
export const CommentWithBackticksAndQuotesSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'Testing backticks and quotes in string: `backticks`, \'quotes\', "double quotes" and ```multiple backticks``` should work' });

/**
 * Testing slashes in string: \backwards\\\ and /forwards/// should work
 */
export const CommentWithSlashesSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'Testing slashes in string: \\backwards\\\\\\ and /forwards/// should work' });

/**
 * Testing expression placeholders in string: ${expression} should work
 */
export const CommentWithExpressionPlaceholdersSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'Testing expression placeholders in string: ${expression} should work' });

/**
 * Testing quotes in string: 'single quote''' and "double quotes""" should work
 */
export const CommentWithQuotesSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'Testing quotes in string: \'single quote\'\'\' and "double quotes""" should work' });

/**
 * Testing reserved characters in string: * inline * and ** inline ** should work
 */
export const CommentWithReservedCharactersSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'Testing reserved characters in string: /* inline */ and /** inline **/ should work' });

/**
 * This is a simple number
 */
export const SimpleIntegerSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'This is a simple number' });

/**
 * This is a simple boolean
 */
export const SimpleBooleanSchema = Schema.Boolean.annotate({ description: 'This is a simple boolean' });

/**
 * This is a simple string
 */
export const SimpleStringSchema = Schema.String.annotate({ description: 'This is a simple string' });

/**
 * A string with non-ascii (unicode) characters valid in typescript identifiers (æøåÆØÅöÔèÈ字符串)
 */
export const NonAsciiStringæøåÆøÅöôêÊ字符串Schema = Schema.String.annotate({ description: 'A string with non-ascii (unicode) characters valid in typescript identifiers (æøåÆØÅöÔèÈ字符串)' });

/**
 * This is a simple file
 */
export const SimpleFileSchema = Schema.Uint8Array.annotate({ description: 'This is a simple file' });

/**
 * This is a simple string
 */
export const SimpleStringWithPatternSchema = Schema.Union([Schema.String.check(Schema.isMaxLength(64), Schema.isPattern(new RegExp('^[a-zA-Z0-9_]*$'))), Schema.Null]).annotate({ description: 'This is a simple string' });

/**
 * This is a simple enum with strings
 */
export const EnumWithStringsSchema = Schema.Union([
  Schema.Literal('Success'),
  Schema.Literal('Warning'),
  Schema.Literal('Error'),
  Schema.Literal('\'Single Quote\''),
  Schema.Literal('"Double Quotes"'),
  Schema.Literal('Non-ascii: øæåôöØÆÅÔÖ字符串')
]).annotate({ description: 'This is a simple enum with strings' });

export const EnumWithReplacedCharactersSchema = Schema.Union([
  Schema.Literal('\'Single Quote\''),
  Schema.Literal('"Double Quotes"'),
  Schema.Literal('øæåôöØÆÅÔÖ字符串'),
  Schema.Literal(3.1).check(Schema.isFinite()),
  Schema.Literal('')
]);

/**
 * This is a simple enum with numbers
 */
export const EnumWithNumbersSchema = Schema.Union([
  Schema.Literal(1).check(Schema.isFinite()),
  Schema.Literal(2).check(Schema.isFinite()),
  Schema.Literal(3).check(Schema.isFinite()),
  Schema.Literal(1.1).check(Schema.isFinite()),
  Schema.Literal(1.2).check(Schema.isFinite()),
  Schema.Literal(1.3).check(Schema.isFinite()),
  Schema.Literal(100).check(Schema.isFinite()),
  Schema.Literal(200).check(Schema.isFinite()),
  Schema.Literal(300).check(Schema.isFinite()),
  Schema.Literal(-100).check(Schema.isFinite()),
  Schema.Literal(-200).check(Schema.isFinite()),
  Schema.Literal(-300).check(Schema.isFinite()),
  Schema.Literal(-1.1).check(Schema.isFinite()),
  Schema.Literal(-1.2).check(Schema.isFinite()),
  Schema.Literal(-1.3).check(Schema.isFinite())
]).check(Schema.isFinite()).annotate({ description: 'This is a simple enum with numbers' });

/**
 * Success=1,Warning=2,Error=3
 */
export const EnumFromDescriptionSchema = Schema.Number.check(Schema.isFinite()).annotate({ description: 'Success=1,Warning=2,Error=3' });

/**
 * This is a simple enum with numbers
 */
export const EnumWithExtensionsSchema = Schema.Union([
  Schema.Literal(200).check(Schema.isFinite()).annotate({ title: 'CUSTOM_SUCCESS', description: 'Used when the status of something is successful' }),
  Schema.Literal(400).check(Schema.isFinite()).annotate({ title: 'CUSTOM_WARNING', description: 'Used when the status of something has a warning' }),
  Schema.Literal(500).check(Schema.isFinite()).annotate({ title: 'CUSTOM_ERROR', description: 'Used when the status of something has an error' })
]).check(Schema.isFinite()).annotate({ description: 'This is a simple enum with numbers' });

export const EnumWithXEnumNamesSchema = Schema.Union([
  Schema.Literal(0).check(Schema.isFinite()).annotate({ title: 'zero' }),
  Schema.Literal(1).check(Schema.isFinite()).annotate({ title: 'one' }),
  Schema.Literal(2).check(Schema.isFinite()).annotate({ title: 'two' })
]).check(Schema.isFinite());

/**
 * This is a simple array with numbers
 */
export const ArrayWithNumbersSchema = Schema.Array(Schema.Number.check(Schema.isInt())).annotate({ description: 'This is a simple array with numbers' });

/**
 * This is a simple array with booleans
 */
export const ArrayWithBooleansSchema = Schema.Array(Schema.Boolean).annotate({ description: 'This is a simple array with booleans' });

/**
 * This is a simple array with strings
 */
export const ArrayWithStringsSchema = Schema.Array(Schema.String).annotate({ description: 'This is a simple array with strings' });

/**
 * This is a simple array with properties
 */
export const ArrayWithPropertiesSchema = Schema.Array(Schema.Struct({
  '16x16': Schema.optionalKey(CamelCaseCommentWithBreaksSchema.check(Schema.isInt())),
  bar: Schema.optionalKey(Schema.String)
})).annotate({ description: 'This is a simple array with properties' });

/**
 * This is a simple array with any of properties
 */
export const ArrayWithAnyOfPropertiesSchema = Schema.Array(Schema.Struct({
  foo: Schema.optionalKey(Schema.String)
})).annotate({ description: 'This is a simple array with any of properties' });

export const AnyOfAnyAndNullSchema = Schema.Struct({
  data: Schema.optionalKey(Schema.Union([Schema.Unknown, Schema.Null]))
});

/**
 * This is a simple array with any of properties
 */
export const AnyOfArraysSchema = Schema.Struct({
  results: Schema.optionalKey(Schema.Array(Schema.Struct({
    foo: Schema.optionalKey(Schema.String)
  })))
}).annotate({ description: 'This is a simple array with any of properties' });

/**
 * This is a string dictionary
 */
export const DictionaryWithStringSchema = Schema.Record(Schema.String, Schema.String).annotate({ description: 'This is a string dictionary' });

export const DictionaryWithPropertiesAndAdditionalPropertiesSchema = Schema.StructWithRest(Schema.Struct({
  foo: Schema.optionalKey(Schema.Number.check(Schema.isFinite())),
  bar: Schema.optionalKey(Schema.Boolean)
}), [Schema.Record(Schema.String.check(Schema.isPattern(new RegExp('^(?!(?:foo|bar)$)[\\s\\S]*$'))), Schema.String)]);

/**
 * This is a string dictionary
 */
export const DictionaryWithDictionarySchema = Schema.Record(Schema.String, Schema.Record(Schema.String, Schema.String)).annotate({ description: 'This is a string dictionary' });

/**
 * This is a complex dictionary
 */
export const DictionaryWithPropertiesSchema = Schema.Record(Schema.String, Schema.Struct({
  foo: Schema.optionalKey(Schema.String),
  bar: Schema.optionalKey(Schema.String)
})).annotate({ description: 'This is a complex dictionary' });

/**
 * This is a model with one number property
 */
export const ModelWithIntegerSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.Number.check(Schema.isInt()).annotate({ description: 'This is a simple number property' }))
}).annotate({ description: 'This is a model with one number property' });

/**
 * This is a model with one boolean property
 */
export const ModelWithBooleanSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.Boolean.annotate({ description: 'This is a simple boolean property' }))
}).annotate({ description: 'This is a model with one boolean property' });

/**
 * This is a model with one string property
 */
export const ModelWithStringSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.String.annotate({ description: 'This is a simple string property' }))
}).annotate({ description: 'This is a model with one string property' });

/**
 * This is a simple reference
 */
export const SimpleReferenceSchema = ModelWithStringSchema.annotate({ description: 'This is a simple reference' });

/**
 * This is a simple array with references
 */
export const ArrayWithReferencesSchema = Schema.Array(ModelWithStringSchema).annotate({ description: 'This is a simple array with references' });

/**
 * This is a simple array containing an array
 */
export const ArrayWithArraySchema = Schema.Array(Schema.Array(ModelWithStringSchema)).annotate({ description: 'This is a simple array containing an array' });

/**
 * This is a string reference
 */
export const DictionaryWithReferenceSchema = Schema.Record(Schema.String, ModelWithStringSchema).annotate({ description: 'This is a string reference' });

/**
 * This is a complex dictionary
 */
export const DictionaryWithArraySchema = Schema.Record(Schema.String, Schema.Array(ModelWithStringSchema)).annotate({ description: 'This is a complex dictionary' });

/**
 * This is a model with one string property
 */
export const ModelWithStringErrorSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.String.annotate({ description: 'This is a simple string property' }))
}).annotate({ description: 'This is a model with one string property' });

/**
 * `Comment` or `VoiceComment`. The JSON object for adding voice comments to tickets is different. See [Adding voice comments to tickets](/documentation/ticketing/managing-tickets/adding-voice-comments-to-tickets)
 */
export const ModelFromZendeskSchema = Schema.String.annotate({ description: '`Comment` or `VoiceComment`. The JSON object for adding voice comments to tickets is different. See [Adding voice comments to tickets](/documentation/ticketing/managing-tickets/adding-voice-comments-to-tickets)' });

/**
 * This is a model with one string property
 */
export const ModelWithNullableStringSchema = Schema.Struct({
  nullableProp1: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a simple string property' })),
  nullableRequiredProp1: Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a simple string property' }),
  nullableProp2: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a simple string property' })),
  nullableRequiredProp2: Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a simple string property' }),
  'foo_bar-enum': Schema.optionalKey(Schema.Union([
    Schema.Literal('Success'),
    Schema.Literal('Warning'),
    Schema.Literal('Error'),
    Schema.Literal('ØÆÅ字符串')
  ]).annotate({ description: 'This is a simple enum with strings' }))
}).annotate({ description: 'This is a model with one string property' });

/**
 * This is a model with one enum
 */
export const ModelWithEnumSchema = Schema.Struct({
  'foo_bar-enum': Schema.optionalKey(Schema.Union([
    Schema.Literal('Success'),
    Schema.Literal('Warning'),
    Schema.Literal('Error'),
    Schema.Literal('ØÆÅ字符串')
  ]).annotate({ description: 'This is a simple enum with strings' })),
  statusCode: Schema.optionalKey(Schema.Union([
    Schema.Literal('100'),
    Schema.Literal('200 FOO'),
    Schema.Literal('300 FOO_BAR'),
    Schema.Literal('400 foo-bar'),
    Schema.Literal('500 foo.bar'),
    Schema.Literal('600 foo&bar')
  ]).annotate({ description: 'These are the HTTP error code enums' })),
  bool: Schema.optionalKey(Schema.Literal(true).annotate({ description: 'Simple boolean enum' }))
}).annotate({ description: 'This is a model with one enum' });

/**
 * This is a model with one enum with escaped name
 */
export const ModelWithEnumWithHyphenSchema = Schema.Struct({
  'foo-bar-baz-qux': Schema.optionalKey(Schema.Literal('3.0').annotate({ title: 'Foo-Bar-Baz-Qux' }))
}).annotate({ description: 'This is a model with one enum with escaped name' });

/**
 * This is a model with one enum
 */
export const ModelWithEnumFromDescriptionSchema = Schema.Struct({
  test: Schema.optionalKey(Schema.Number.check(Schema.isInt()).annotate({ description: 'Success=1,Warning=2,Error=3' }))
}).annotate({ description: 'This is a model with one enum' });

/**
 * This is a model with nested enums
 */
export const ModelWithNestedEnumsSchema = Schema.Struct({
  dictionaryWithEnum: Schema.optionalKey(Schema.Record(Schema.String, Schema.Union([
    Schema.Literal('Success'),
    Schema.Literal('Warning'),
    Schema.Literal('Error')
  ]))),
  dictionaryWithEnumFromDescription: Schema.optionalKey(Schema.Record(Schema.String, Schema.Number.check(Schema.isInt()).annotate({ description: 'Success=1,Warning=2,Error=3' }))),
  arrayWithEnum: Schema.optionalKey(Schema.Array(Schema.Union([
    Schema.Literal('Success'),
    Schema.Literal('Warning'),
    Schema.Literal('Error')
  ]))),
  arrayWithDescription: Schema.optionalKey(Schema.Array(Schema.Number.check(Schema.isInt()).annotate({ description: 'Success=1,Warning=2,Error=3' }))),
  'foo_bar-enum': Schema.optionalKey(Schema.Union([
    Schema.Literal('Success'),
    Schema.Literal('Warning'),
    Schema.Literal('Error'),
    Schema.Literal('ØÆÅ字符串')
  ]).annotate({ description: 'This is a simple enum with strings' }))
}).annotate({ description: 'This is a model with nested enums' });

/**
 * This is a model with one property containing an array
 */
export const ModelWithArraySchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.Array(ModelWithStringSchema)),
  propWithFile: Schema.optionalKey(Schema.Array(Schema.Uint8Array)),
  propWithNumber: Schema.optionalKey(Schema.Array(Schema.Number.check(Schema.isFinite())))
}).annotate({ description: 'This is a model with one property containing an array' });

/**
 * This is a model with one property containing a dictionary
 */
export const ModelWithDictionarySchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.Record(Schema.String, Schema.String))
}).annotate({ description: 'This is a model with one property containing a dictionary' });

/**
 * This is a deprecated model with a deprecated property
 *
 * @deprecated
 */
export const DeprecatedModelSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.String.annotate({ description: 'This is a deprecated property' }))
}).annotate({ description: 'This is a deprecated model with a deprecated property' });

/**
 * This is a model with one property containing a circular reference
 */
export const ModelWithCircularReferenceSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.suspend((): Schema.Codec<ModelWithCircularReference> => ModelWithCircularReferenceSchema))
}).annotate({ description: 'This is a model with one property containing a circular reference' });

/**
 * This is a model with one property with a 'one of' relationship
 */
export const CompositionWithOneOfSchema = Schema.Struct({
  propA: Schema.optionalKey(Schema.Union([
    ModelWithStringSchema,
    ModelWithEnumSchema,
    ModelWithArraySchema,
    ModelWithDictionarySchema
  ]))
}).annotate({ description: 'This is a model with one property with a \'one of\' relationship' });

/**
 * This is a model with one property with a 'one of' relationship where the options are not $ref
 */
export const CompositionWithOneOfAnonymousSchema = Schema.Struct({
  propA: Schema.optionalKey(Schema.Union([
    Schema.Struct({
      propA: Schema.optionalKey(Schema.String)
    }).annotate({ description: 'Anonymous object type' }),
    Schema.String.annotate({ description: 'Anonymous string type' }),
    Schema.Number.check(Schema.isInt()).annotate({ description: 'Anonymous integer type' })
  ]))
}).annotate({ description: 'This is a model with one property with a \'one of\' relationship where the options are not $ref' });

/**
 * Circle
 */
export const ModelCircleSchema = Schema.Struct({
  kind: Schema.String,
  radius: Schema.optionalKey(Schema.Number.check(Schema.isFinite()))
}).annotate({ description: 'Circle' });

/**
 * Square
 */
export const ModelSquareSchema = Schema.Struct({
  kind: Schema.String,
  sideLength: Schema.optionalKey(Schema.Number.check(Schema.isFinite()))
}).annotate({ description: 'Square' });

/**
 * This is a model with one property with a 'one of' relationship where the options are not $ref
 */
export const CompositionWithOneOfDiscriminatorSchema = Schema.Union([ModelCircleSchema, ModelSquareSchema]).annotate({ description: 'This is a model with one property with a \'one of\' relationship where the options are not $ref' });

/**
 * This is a model with one property with a 'any of' relationship
 */
export const CompositionWithAnyOfSchema = Schema.Struct({
  propA: Schema.optionalKey(Schema.Union([
    ModelWithStringSchema,
    ModelWithEnumSchema,
    ModelWithArraySchema,
    ModelWithDictionarySchema
  ]))
}).annotate({ description: 'This is a model with one property with a \'any of\' relationship' });

/**
 * This is a model with one property with a 'any of' relationship where the options are not $ref
 */
export const CompositionWithAnyOfAnonymousSchema = Schema.Struct({
  propA: Schema.optionalKey(Schema.Union([
    Schema.Struct({
      propA: Schema.optionalKey(Schema.String)
    }).annotate({ description: 'Anonymous object type' }),
    Schema.String.annotate({ description: 'Anonymous string type' }),
    Schema.Number.check(Schema.isInt()).annotate({ description: 'Anonymous integer type' })
  ]))
}).annotate({ description: 'This is a model with one property with a \'any of\' relationship where the options are not $ref' });

/**
 * This is a model with nested 'any of' property with a type null
 */
export const CompositionWithNestedAnyAndTypeNullSchema = Schema.Struct({
  propA: Schema.optionalKey(Schema.Union([Schema.Array(ModelWithDictionarySchema), Schema.Array(ModelWithArraySchema)]))
}).annotate({ description: 'This is a model with nested \'any of\' property with a type null' });

export const _3eNum1ПериодSchema = Schema.Union([Schema.Literal('Bird'), Schema.Literal('Dog')]);

export const ConstValueSchema = Schema.Literal('ConstValue');

/**
 * This is a model with one property with a 'any of' relationship where the options are not $ref
 */
export const CompositionWithNestedAnyOfAndNullSchema = Schema.Struct({
  propA: Schema.optionalKey(Schema.Union([Schema.Array(_3eNum1ПериодSchema), Schema.Null]).annotate({ title: 'Scopes' }))
}).annotate({ description: 'This is a model with one property with a \'any of\' relationship where the options are not $ref' });

/**
 * This is a model with one property with a 'one of' relationship
 */
export const CompositionWithOneOfAndNullableSchema = Schema.Struct({
  propA: Schema.optionalKey(Schema.Union([
    Schema.Struct({
      boolean: Schema.optionalKey(Schema.Boolean)
    }),
    ModelWithEnumSchema,
    ModelWithArraySchema,
    ModelWithDictionarySchema,
    Schema.Null
  ]))
}).annotate({ description: 'This is a model with one property with a \'one of\' relationship' });

/**
 * This is a model that contains a simple dictionary within composition
 */
export const CompositionWithOneOfAndSimpleDictionarySchema = Schema.Struct({
  propA: Schema.optionalKey(Schema.Union([Schema.Boolean, Schema.Record(Schema.String, Schema.Number.check(Schema.isFinite()))]))
}).annotate({ description: 'This is a model that contains a simple dictionary within composition' });

/**
 * This is a model that contains a dictionary of simple arrays within composition
 */
export const CompositionWithOneOfAndSimpleArrayDictionarySchema = Schema.Struct({
  propA: Schema.optionalKey(Schema.Union([Schema.Boolean, Schema.Record(Schema.String, Schema.Array(Schema.Boolean))]))
}).annotate({ description: 'This is a model that contains a dictionary of simple arrays within composition' });

/**
 * This is a model that contains a dictionary of complex arrays (composited) within composition
 */
export const CompositionWithOneOfAndComplexArrayDictionarySchema = Schema.Struct({
  propA: Schema.optionalKey(Schema.Union([Schema.Boolean, Schema.Record(Schema.String, Schema.Array(Schema.Number.check(Schema.isFinite())))]))
}).annotate({ description: 'This is a model that contains a dictionary of complex arrays (composited) within composition' });

/**
 * This is a model with one property with a 'all of' relationship
 */
export const CompositionWithAllOfAndNullableSchema = Schema.Struct({
  propA: Schema.optionalKey(Schema.Union([Schema.Struct({
      boolean: Schema.optionalKey(Schema.Boolean),
      'foo_bar-enum': Schema.optionalKey(Schema.Union([
        Schema.Literal('Success'),
        Schema.Literal('Warning'),
        Schema.Literal('Error'),
        Schema.Literal('ØÆÅ字符串')
      ]).annotate({ description: 'This is a simple enum with strings' })),
      statusCode: Schema.optionalKey(Schema.Union([
        Schema.Literal('100'),
        Schema.Literal('200 FOO'),
        Schema.Literal('300 FOO_BAR'),
        Schema.Literal('400 foo-bar'),
        Schema.Literal('500 foo.bar'),
        Schema.Literal('600 foo&bar')
      ]).annotate({ description: 'These are the HTTP error code enums' })),
      bool: Schema.optionalKey(Schema.Literal(true).annotate({ description: 'Simple boolean enum' })),
      prop: Schema.optionalKey(Schema.Never),
      propWithFile: Schema.optionalKey(Schema.Array(Schema.Uint8Array)),
      propWithNumber: Schema.optionalKey(Schema.Array(Schema.Number.check(Schema.isFinite())))
    }), Schema.Null]))
}).annotate({ description: 'This is a model with one property with a \'all of\' relationship' });

/**
 * This is a model with one property with a 'any of' relationship
 */
export const CompositionWithAnyOfAndNullableSchema = Schema.Struct({
  propA: Schema.optionalKey(Schema.Union([
    Schema.Struct({
      boolean: Schema.optionalKey(Schema.Boolean)
    }),
    ModelWithEnumSchema,
    ModelWithArraySchema,
    ModelWithDictionarySchema,
    Schema.Null
  ]))
}).annotate({ description: 'This is a model with one property with a \'any of\' relationship' });

/**
 * This is a base model with two simple optional properties
 */
export const CompositionBaseModelSchema = Schema.Struct({
  firstName: Schema.optionalKey(Schema.String),
  lastname: Schema.optionalKey(Schema.String)
}).annotate({ description: 'This is a base model with two simple optional properties' });

/**
 * This is a model that extends the base model
 */
export const CompositionExtendedModelSchema = Schema.Struct({
  firstName: Schema.String,
  lastname: Schema.String,
  age: Schema.Number.check(Schema.isFinite())
}).annotate({ description: 'This is a model that extends the base model' });

/**
 * This is a model with one nested property
 */
export const ModelWithPropertiesSchema = Schema.Struct({
  required: Schema.String,
  requiredAndReadOnly: Schema.String,
  requiredAndNullable: Schema.Union([Schema.String, Schema.Null]),
  string: Schema.optionalKey(Schema.String),
  number: Schema.optionalKey(Schema.Number.check(Schema.isFinite())),
  boolean: Schema.optionalKey(Schema.Boolean),
  reference: Schema.optionalKey(ModelWithStringSchema),
  'property with space': Schema.optionalKey(Schema.String),
  default: Schema.optionalKey(Schema.String),
  try: Schema.optionalKey(Schema.String),
  '@namespace.string': Schema.optionalKey(Schema.String),
  '@namespace.integer': Schema.optionalKey(Schema.Number.check(Schema.isInt()))
}).annotate({ description: 'This is a model with one nested property' });

/**
 * This is a model with one property containing a reference
 */
export const ModelWithReferenceSchema = Schema.Struct({
  prop: Schema.optionalKey(ModelWithPropertiesSchema)
}).annotate({ description: 'This is a model with one property containing a reference' });

/**
 * This is a model with one nested property
 */
export const ModelWithNestedPropertiesSchema = Schema.Struct({
  first: Schema.Union([Schema.Struct({
      second: Schema.Union([Schema.Struct({
          third: Schema.Union([Schema.String, Schema.Null])
        }), Schema.Null])
    }), Schema.Null])
}).annotate({ description: 'This is a model with one nested property' });

/**
 * This is a model with duplicated properties
 */
export const ModelWithDuplicatePropertiesSchema = Schema.Struct({
  prop: Schema.optionalKey(ModelWithStringSchema)
}).annotate({ description: 'This is a model with duplicated properties' });

/**
 * This is a model with ordered properties
 */
export const ModelWithOrderedPropertiesSchema = Schema.Struct({
  zebra: Schema.optionalKey(Schema.String),
  apple: Schema.optionalKey(Schema.String),
  hawaii: Schema.optionalKey(Schema.String)
}).annotate({ description: 'This is a model with ordered properties' });

/**
 * This is a model with duplicated imports
 */
export const ModelWithDuplicateImportsSchema = Schema.Struct({
  propA: Schema.optionalKey(ModelWithStringSchema),
  propB: Schema.optionalKey(ModelWithStringSchema),
  propC: Schema.optionalKey(ModelWithStringSchema)
}).annotate({ description: 'This is a model with duplicated imports' });

/**
 * This is a model that extends another model
 */
export const ModelThatExtendsSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.String.annotate({ description: 'This is a simple string property' })),
  propExtendsA: Schema.optionalKey(Schema.String),
  propExtendsB: Schema.optionalKey(ModelWithStringSchema)
}).annotate({ description: 'This is a model that extends another model' });

/**
 * This is a model that extends another model
 */
export const ModelThatExtendsExtendsSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.String.annotate({ description: 'This is a simple string property' })),
  propExtendsA: Schema.optionalKey(Schema.String),
  propExtendsB: Schema.optionalKey(ModelWithStringSchema),
  propExtendsC: Schema.optionalKey(Schema.String),
  propExtendsD: Schema.optionalKey(ModelWithStringSchema)
}).annotate({ description: 'This is a model that extends another model' });

/**
 * This is a model that contains a some patterns
 */
export const ModelWithPatternSchema = Schema.Struct({
  key: Schema.String.check(Schema.isMaxLength(64), Schema.isPattern(new RegExp('^[a-zA-Z0-9_]*$'))),
  name: Schema.String.check(Schema.isMaxLength(255)),
  enabled: Schema.optionalKey(Schema.Boolean),
  modified: Schema.optionalKey(Schema.String.check(Schema.makeFilter(value => {
    if (!/^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))[tT](?:[01]\d|2[0-3]):[0-5]\d:(?:[0-5]\d|60)(?:\.\d+)?(?:[zZ]|[+-](?:[01]\d|2[0-3]):[0-5]\d)$/.test(value)) {
      return false;
    }
    if (!value.includes(':60')) {
      return true;
    }
    const parsed = new globalThis.Date(value.replace(':60', ':59'));
    if (parsed.getUTCHours() !== 23 || parsed.getUTCMinutes() !== 59) {
      return false;
    }
    return parsed.getUTCMonth() === 5 && parsed.getUTCDate() === 30 || parsed.getUTCMonth() === 11 && parsed.getUTCDate() === 31;
  }, { expected: 'an RFC 3339 date-time' })).annotate({ format: 'date-time' })),
  id: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^\\d{2}-\\d{3}-\\d{4}$')))),
  text: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^\\w+$')))),
  patternWithSingleQuotes: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^[a-zA-Z0-9\']*$')))),
  patternWithNewline: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('aaa\\nbbb')))),
  patternWithBacktick: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('aaa`bbb')))),
  patternWithUnicode: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^\\p{L}+$'))))
}).annotate({ description: 'This is a model that contains a some patterns' });

export const FileSchema = Schema.Struct({
  id: Schema.optionalKey(Schema.String.check(Schema.isMinLength(1)).annotate({ title: 'Id' })),
  updated_at: Schema.optionalKey(Schema.String.check(Schema.makeFilter(value => {
    if (!/^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))[tT](?:[01]\d|2[0-3]):[0-5]\d:(?:[0-5]\d|60)(?:\.\d+)?(?:[zZ]|[+-](?:[01]\d|2[0-3]):[0-5]\d)$/.test(value)) {
      return false;
    }
    if (!value.includes(':60')) {
      return true;
    }
    const parsed = new globalThis.Date(value.replace(':60', ':59'));
    if (parsed.getUTCHours() !== 23 || parsed.getUTCMinutes() !== 59) {
      return false;
    }
    return parsed.getUTCMonth() === 5 && parsed.getUTCDate() === 30 || parsed.getUTCMonth() === 11 && parsed.getUTCDate() === 31;
  }, { expected: 'an RFC 3339 date-time' })).annotate({ title: 'Updated at', format: 'date-time' })),
  created_at: Schema.optionalKey(Schema.String.check(Schema.makeFilter(value => {
    if (!/^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))[tT](?:[01]\d|2[0-3]):[0-5]\d:(?:[0-5]\d|60)(?:\.\d+)?(?:[zZ]|[+-](?:[01]\d|2[0-3]):[0-5]\d)$/.test(value)) {
      return false;
    }
    if (!value.includes(':60')) {
      return true;
    }
    const parsed = new globalThis.Date(value.replace(':60', ':59'));
    if (parsed.getUTCHours() !== 23 || parsed.getUTCMinutes() !== 59) {
      return false;
    }
    return parsed.getUTCMonth() === 5 && parsed.getUTCDate() === 30 || parsed.getUTCMonth() === 11 && parsed.getUTCDate() === 31;
  }, { expected: 'an RFC 3339 date-time' })).annotate({ title: 'Created at', format: 'date-time' })),
  mime: Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(24)).annotate({ title: 'Mime' }),
  file: Schema.optionalKey(Schema.String.check(Schema.makeFilter(value => URL.canParse(value), { expected: 'a valid URL' })).annotate({ title: 'File', format: 'uri' }))
});

export const DefaultSchema = Schema.Struct({
  name: Schema.optionalKey(Schema.String)
});

export const PageableSchema = Schema.Struct({
  page: Schema.optionalKey(Schema.Number.check(Schema.isInt(), Schema.isGreaterThanOrEqualTo(0)).annotate({ format: 'int32' })),
  size: Schema.optionalKey(Schema.Number.check(Schema.isInt(), Schema.isGreaterThanOrEqualTo(1)).annotate({ format: 'int32' })),
  sort: Schema.optionalKey(Schema.Array(Schema.String))
});

/**
 * This is a free-form object without additionalProperties.
 */
export const FreeFormObjectWithoutAdditionalPropertiesSchema = Schema.Record(Schema.String, Schema.Unknown).annotate({ description: 'This is a free-form object without additionalProperties.' });

/**
 * This is a free-form object with additionalProperties: true.
 */
export const FreeFormObjectWithAdditionalPropertiesEqTrueSchema = Schema.Record(Schema.String, Schema.Unknown).annotate({ description: 'This is a free-form object with additionalProperties: true.' });

/**
 * This is a free-form object with additionalProperties: {}.
 */
export const FreeFormObjectWithAdditionalPropertiesEqEmptyObjectSchema = Schema.Record(Schema.String, Schema.Unknown).annotate({ description: 'This is a free-form object with additionalProperties: {}.' });

export const ModelWithConstSchema = Schema.Struct({
  String: Schema.optionalKey(Schema.Literal('String')),
  number: Schema.optionalKey(Schema.Literal(0).check(Schema.isFinite())),
  null: Schema.optionalKey(Schema.Null),
  withType: Schema.optionalKey(Schema.Literal('Some string'))
});

/**
 * This is a model with one property and additionalProperties: true
 */
export const ModelWithAdditionalPropertiesEqTrueSchema = Schema.StructWithRest(Schema.Struct({
  prop: Schema.optionalKey(Schema.String.annotate({ description: 'This is a simple string property' }))
}), [Schema.Record(Schema.String.check(Schema.isPattern(new RegExp('^(?!(?:prop)$)[\\s\\S]*$'))), Schema.Unknown)]).annotate({ description: 'This is a model with one property and additionalProperties: true' });

export const NestedAnyOfArraysNullableSchema = Schema.Struct({
  nullableArray: Schema.optionalKey(Schema.Union([Schema.Array(Schema.String), Schema.Null]))
});

/**
 * An object that can be null
 */
export const NullableObjectSchema = Schema.Union([Schema.Struct({
    foo: Schema.optionalKey(Schema.String)
  }), Schema.Null]).annotate({ description: 'An object that can be null' });

/**
 * Some % character
 */
export const CharactersInDescriptionSchema = Schema.String.annotate({ description: 'Some % character' });

export const ModelWithNullableObjectSchema = Schema.Struct({
  data: Schema.optionalKey(NullableObjectSchema)
});

/**
 * An object with additional properties that can be null (anyOf ref + null)
 */
export const ModelWithAdditionalPropertiesRefSchema = Schema.Record(Schema.String, Schema.Union([NullableObjectSchema, Schema.Null])).annotate({ description: 'An object with additional properties that can be null (anyOf ref + null)' });

export const ModelWithOneOfEnumSchema = Schema.Union([
  Schema.Struct({
    foo: Schema.Literal('Bar')
  }),
  Schema.Struct({
    foo: Schema.Literal('Baz')
  }),
  Schema.Struct({
    foo: Schema.Literal('Qux')
  }),
  Schema.Struct({
    content: Schema.String.check(Schema.makeFilter(value => {
      if (!/^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))[tT](?:[01]\d|2[0-3]):[0-5]\d:(?:[0-5]\d|60)(?:\.\d+)?(?:[zZ]|[+-](?:[01]\d|2[0-3]):[0-5]\d)$/.test(value)) {
        return false;
      }
      if (!value.includes(':60')) {
        return true;
      }
      const parsed = new globalThis.Date(value.replace(':60', ':59'));
      if (parsed.getUTCHours() !== 23 || parsed.getUTCMinutes() !== 59) {
        return false;
      }
      return parsed.getUTCMonth() === 5 && parsed.getUTCDate() === 30 || parsed.getUTCMonth() === 11 && parsed.getUTCDate() === 31;
    }, { expected: 'an RFC 3339 date-time' })).annotate({ format: 'date-time' }),
    foo: Schema.Literal('Quux')
  }),
  Schema.Struct({
    content: Schema.Tuple([Schema.String.check(Schema.makeFilter(value => {
        if (!/^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))[tT](?:[01]\d|2[0-3]):[0-5]\d:(?:[0-5]\d|60)(?:\.\d+)?(?:[zZ]|[+-](?:[01]\d|2[0-3]):[0-5]\d)$/.test(value)) {
          return false;
        }
        if (!value.includes(':60')) {
          return true;
        }
        const parsed = new globalThis.Date(value.replace(':60', ':59'));
        if (parsed.getUTCHours() !== 23 || parsed.getUTCMinutes() !== 59) {
          return false;
        }
        return parsed.getUTCMonth() === 5 && parsed.getUTCDate() === 30 || parsed.getUTCMonth() === 11 && parsed.getUTCDate() === 31;
      }, { expected: 'an RFC 3339 date-time' })).annotate({ format: 'date-time' }), Schema.String]).check(Schema.isMinLength(2), Schema.isMaxLength(2)),
    foo: Schema.Literal('Corge')
  })
]);

export const ModelWithNestedArrayEnumsDataFooSchema = Schema.Union([Schema.Literal('foo'), Schema.Literal('bar')]);

export const ModelWithNestedArrayEnumsDataBarSchema = Schema.Union([Schema.Literal('baz'), Schema.Literal('qux')]);

export const ModelWithNestedArrayEnumsDataSchema = Schema.Struct({
  foo: Schema.optionalKey(Schema.Array(ModelWithNestedArrayEnumsDataFooSchema)),
  bar: Schema.optionalKey(Schema.Array(ModelWithNestedArrayEnumsDataBarSchema))
});

export const ModelWithNestedArrayEnumsSchema = Schema.Struct({
  array_strings: Schema.optionalKey(Schema.Array(Schema.String)),
  data: Schema.optionalKey(ModelWithNestedArrayEnumsDataSchema)
});

export const ModelWithNestedCompositionEnumsSchema = Schema.Struct({
  foo: Schema.optionalKey(ModelWithNestedArrayEnumsDataFooSchema)
});

export const ModelWithReadOnlyAndWriteOnlySchema = Schema.Struct({
  foo: Schema.String,
  bar: Schema.String
});

/**
 * This is a model with one property containing an array
 */
export const ModelWithArrayReadOnlyAndWriteOnlySchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.Array(ModelWithReadOnlyAndWriteOnlySchema)),
  propWithFile: Schema.optionalKey(Schema.Array(Schema.Uint8Array)),
  propWithNumber: Schema.optionalKey(Schema.Array(Schema.Number.check(Schema.isFinite())))
}).annotate({ description: 'This is a model with one property containing an array' });

export const ModelWithConstantSizeArraySchema = Schema.Tuple([Schema.Number.check(Schema.isFinite()), Schema.Number.check(Schema.isFinite())]).check(Schema.isMinLength(2), Schema.isMaxLength(2));

export const ModelWithAnyOfConstantSizeArraySchema = Schema.Tuple([
  Schema.Union([Schema.Number.check(Schema.isFinite()), Schema.String]),
  Schema.Union([Schema.Number.check(Schema.isFinite()), Schema.String]),
  Schema.Union([Schema.Number.check(Schema.isFinite()), Schema.String])
]).check(Schema.isMinLength(3), Schema.isMaxLength(3));

export const ModelWithPrefixItemsConstantSizeArraySchema = Schema.Tuple([
  ModelWithIntegerSchema,
  Schema.Union([Schema.Number.check(Schema.isFinite()), Schema.String]),
  Schema.String
]);

export const ModelWithAnyOfConstantSizeArrayNullableSchema = Schema.Tuple([
  Schema.Union([
    Schema.Number.check(Schema.isFinite()),
    Schema.Null,
    Schema.String
  ]),
  Schema.Union([
    Schema.Number.check(Schema.isFinite()),
    Schema.Null,
    Schema.String
  ]),
  Schema.Union([
    Schema.Number.check(Schema.isFinite()),
    Schema.Null,
    Schema.String
  ])
]).check(Schema.isMinLength(3), Schema.isMaxLength(3));

export const ModelWithAnyOfConstantSizeArrayAndIntersectSchema = Schema.Tuple([Schema.Never, Schema.Never]).check(Schema.isMinLength(2), Schema.isMaxLength(2));

export const ModelWithNumericEnumUnionSchema = Schema.Struct({
  value: Schema.optionalKey(Schema.Union([
    Schema.Literal(-10).check(Schema.isFinite()),
    Schema.Literal(-1).check(Schema.isFinite()),
    Schema.Literal(0).check(Schema.isFinite()),
    Schema.Literal(1).check(Schema.isFinite()),
    Schema.Literal(3).check(Schema.isFinite()),
    Schema.Literal(6).check(Schema.isFinite()),
    Schema.Literal(12).check(Schema.isFinite())
  ]).check(Schema.isFinite()).annotate({ description: 'Период' }))
});

/**
 * Some description with `back ticks`
 */
export const ModelWithBackticksInDescriptionSchema = Schema.Struct({
  template: Schema.optionalKey(Schema.String.annotate({ description: 'The template `that` should be used for parsing and importing the contents of the CSV file.\n\n<br/><p>There is one placeholder currently supported:<ul>     <li><b>${x}</b> - refers to the n-th column in the CSV file, e.g. ${1}, ${2}, ...)</li></ul><p>Example of a correct JSON template:</p>\n<pre>\n[\n  {\n    "resourceType": "Asset",\n    "identifier": {\n      "name": "${1}",\n      "domain": {\n        "name": "${2}",\n        "community": {\n          "name": "Some Community"\n        }\n      }\n    },\n    "attributes" : {\n      "00000000-0000-0000-0000-000000003115" : [ {\n        "value" : "${3}"\n      } ],\n      "00000000-0000-0000-0000-000000000222" : [ {\n        "value" : "${4}"\n      } ]\n    }\n  }\n]\n</pre>' }))
}).annotate({ description: 'Some description with `back ticks`' });

/**
 * Model used to test deduplication strategy (unused)
 */
export const ParameterSimpleParameterUnusedSchema = Schema.String.annotate({ description: 'Model used to test deduplication strategy (unused)' });

/**
 * Model used to test deduplication strategy
 */
export const PostServiceWithEmptyTagResponseSchema = Schema.String.annotate({ description: 'Model used to test deduplication strategy' });

/**
 * Model used to test deduplication strategy
 */
export const PostServiceWithEmptyTagResponse2Schema = Schema.String.annotate({ description: 'Model used to test deduplication strategy' });

/**
 * Model used to test deduplication strategy
 */
export const DeleteFooDataSchema = Schema.String.annotate({ description: 'Model used to test deduplication strategy' });

/**
 * Model used to test deduplication strategy
 */
export const DeleteFooData2Schema = Schema.String.annotate({ description: 'Model used to test deduplication strategy' });

/**
 * Model with restricted keyword name
 */
export const ImportSchema = Schema.String.annotate({ description: 'Model with restricted keyword name' });

export const ModelWithAnyOfConstantSizeArrayWithNSizeAndOptionsSchema = Schema.Tuple([Schema.Union([Schema.Number.check(Schema.isFinite()), ImportSchema]), Schema.Union([Schema.Number.check(Schema.isFinite()), ImportSchema])]).check(Schema.isMinLength(2), Schema.isMaxLength(2));

export const SchemaWithFormRestrictedKeysSchema = Schema.Struct({
  description: Schema.optionalKey(Schema.String),
  'x-enum-descriptions': Schema.optionalKey(Schema.String),
  'x-enum-varnames': Schema.optionalKey(Schema.String),
  'x-enumNames': Schema.optionalKey(Schema.String),
  title: Schema.optionalKey(Schema.String),
  object: Schema.optionalKey(Schema.Struct({
    description: Schema.optionalKey(Schema.String),
    'x-enum-descriptions': Schema.optionalKey(Schema.String),
    'x-enum-varnames': Schema.optionalKey(Schema.String),
    'x-enumNames': Schema.optionalKey(Schema.String),
    title: Schema.optionalKey(Schema.String)
  })),
  array: Schema.optionalKey(Schema.Array(Schema.Struct({
    description: Schema.optionalKey(Schema.String),
    'x-enum-descriptions': Schema.optionalKey(Schema.String),
    'x-enum-varnames': Schema.optionalKey(Schema.String),
    'x-enumNames': Schema.optionalKey(Schema.String),
    title: Schema.optionalKey(Schema.String)
  })))
});

/**
 * This schema was giving PascalCase transformations a hard time
 */
export const IoK8sApimachineryPkgApisMetaV1PreconditionsSchema = Schema.Struct({
  resourceVersion: Schema.optionalKey(Schema.String.annotate({ description: 'Specifies the target ResourceVersion' })),
  uid: Schema.optionalKey(Schema.String.annotate({ description: 'Specifies the target UID.' }))
}).annotate({ description: 'This schema was giving PascalCase transformations a hard time' });

/**
 * This schema was giving PascalCase transformations a hard time
 */
export const IoK8sApimachineryPkgApisMetaV1DeleteOptionsSchema = Schema.Struct({
  preconditions: Schema.optionalKey(IoK8sApimachineryPkgApisMetaV1PreconditionsSchema.annotate({ description: 'Must be fulfilled before a deletion is carried out. If not possible, a 409 Conflict status will be returned.' }))
}).annotate({ description: 'This schema was giving PascalCase transformations a hard time' });

export const AdditionalPropertiesUnknownIssueSchema = Schema.Record(Schema.String, Schema.Union([Schema.String, Schema.Number.check(Schema.isFinite())]));

export const AdditionalPropertiesUnknownIssue2Schema = Schema.Record(Schema.String, Schema.Union([Schema.String, Schema.Number.check(Schema.isFinite())]));

export const AdditionalPropertiesUnknownIssue3Schema = Schema.Never;

export const AdditionalPropertiesIntegerIssueSchema = Schema.StructWithRest(Schema.Struct({
  value: Schema.Number.check(Schema.isInt())
}), [Schema.Record(Schema.String.check(Schema.isPattern(new RegExp('^(?!(?:value)$)[\\s\\S]*$'))), Schema.Number.check(Schema.isInt()))]);

export const GenericSchemaDuplicateIssue1SystemBooleanSchema = Schema.Struct({
  item: Schema.optionalKey(Schema.Boolean),
  error: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  hasError: Schema.optionalKey(Schema.Boolean),
  data: Schema.optionalKey(Schema.Struct({}))
});

export const GenericSchemaDuplicateIssue1SystemStringSchema = Schema.Struct({
  item: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  error: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  hasError: Schema.optionalKey(Schema.Boolean)
});

export const OneOfAllOfIssueSchema = Schema.Union([Schema.Union([ConstValueSchema, GenericSchemaDuplicateIssue1SystemBooleanSchema]).check(Schema.makeFilter(Schema.is(_3eNum1ПериодSchema), { expected: 'a value matching this allOf member' })), GenericSchemaDuplicateIssue1SystemStringSchema]);

export const ExternalSharedModelSchema = Schema.Struct({
  id: Schema.String,
  name: Schema.optionalKey(Schema.String)
});

/**
 * External ref to shared model (A)
 */
export const ExternalRefASchema = ExternalSharedModelSchema.annotate({ description: 'External ref to shared model (A)' });

/**
 * External ref to shared model (B)
 */
export const ExternalRefBSchema = ExternalSharedModelSchema.annotate({ description: 'External ref to shared model (B)' });

/**
 * This is a model with one nested property
 */
export const ModelWithPropertiesWritableSchema = Schema.Struct({
  required: Schema.String,
  requiredAndNullable: Schema.Union([Schema.String, Schema.Null]),
  string: Schema.optionalKey(Schema.String),
  number: Schema.optionalKey(Schema.Number.check(Schema.isFinite())),
  boolean: Schema.optionalKey(Schema.Boolean),
  reference: Schema.optionalKey(ModelWithStringSchema),
  'property with space': Schema.optionalKey(Schema.String),
  default: Schema.optionalKey(Schema.String),
  try: Schema.optionalKey(Schema.String)
}).annotate({ description: 'This is a model with one nested property' });

/**
 * This is a model with one property containing a reference
 */
export const ModelWithReferenceWritableSchema = Schema.Struct({
  prop: Schema.optionalKey(ModelWithPropertiesWritableSchema)
}).annotate({ description: 'This is a model with one property containing a reference' });

/**
 * This is a model that contains a some patterns
 */
export const ModelWithPatternWritableSchema = Schema.Struct({
  key: Schema.String.check(Schema.isMaxLength(64), Schema.isPattern(new RegExp('^[a-zA-Z0-9_]*$'))),
  name: Schema.String.check(Schema.isMaxLength(255)),
  id: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^\\d{2}-\\d{3}-\\d{4}$')))),
  text: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^\\w+$')))),
  patternWithSingleQuotes: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^[a-zA-Z0-9\']*$')))),
  patternWithNewline: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('aaa\\nbbb')))),
  patternWithBacktick: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('aaa`bbb')))),
  patternWithUnicode: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^\\p{L}+$'))))
}).annotate({ description: 'This is a model that contains a some patterns' });

export const FileWritableSchema = Schema.Struct({
  mime: Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(24)).annotate({ title: 'Mime' })
});

export const ModelWithReadOnlyAndWriteOnlyWritableSchema = Schema.Struct({
  foo: Schema.String,
  baz: Schema.String
});

/**
 * This is a model with one property containing an array
 */
export const ModelWithArrayReadOnlyAndWriteOnlyWritableSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.Array(ModelWithReadOnlyAndWriteOnlyWritableSchema)),
  propWithFile: Schema.optionalKey(Schema.Array(Schema.Uint8Array)),
  propWithNumber: Schema.optionalKey(Schema.Array(Schema.Number.check(Schema.isFinite())))
}).annotate({ description: 'This is a model with one property containing an array' });

export const ModelWithAnyOfConstantSizeArrayWithNSizeAndOptionsWritableSchema = Schema.Tuple([Schema.Union([Schema.Number.check(Schema.isFinite()), ImportSchema]), Schema.Union([Schema.Number.check(Schema.isFinite()), ImportSchema])]).check(Schema.isMinLength(2), Schema.isMaxLength(2));

export const AdditionalPropertiesUnknownIssueWritableSchema = Schema.Record(Schema.String, Schema.Union([Schema.String, Schema.Number.check(Schema.isFinite())]));

export const GenericSchemaDuplicateIssue1SystemBooleanWritableSchema = Schema.Struct({
  item: Schema.optionalKey(Schema.Boolean),
  error: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  data: Schema.optionalKey(Schema.Struct({}))
});

export const GenericSchemaDuplicateIssue1SystemStringWritableSchema = Schema.Struct({
  item: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  error: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null]))
});

export const OneOfAllOfIssueWritableSchema = Schema.Union([Schema.Union([ConstValueSchema, GenericSchemaDuplicateIssue1SystemBooleanWritableSchema]).check(Schema.makeFilter(Schema.is(_3eNum1ПериодSchema), { expected: 'a value matching this allOf member' })), GenericSchemaDuplicateIssue1SystemStringWritableSchema]);

/**
 * This is a reusable parameter
 */
export const SimpleParameterSchema = Schema.String.annotate({ description: 'This is a reusable parameter' });

export const CompositionWithOneOfAndPropertiesSchema = Schema.Union([Schema.Struct({
    foo: SimpleParameterSchema
  }), Schema.Struct({
    bar: NonAsciiStringæøåÆøÅöôêÊ字符串Schema
  })]).check(Schema.makeFilter(Schema.is(Schema.Struct({
  baz: Schema.Union([Schema.Number.check(Schema.isInt(), Schema.isGreaterThanOrEqualTo(0)).annotate({ format: 'uint16' }), Schema.Null]).annotate({ format: 'uint16' }),
  qux: Schema.Number.check(Schema.isInt(), Schema.isGreaterThanOrEqualTo(0)).annotate({ format: 'uint8' })
})), { expected: 'a value matching this allOf member' }));

export const ModelWithOneOfAndPropertiesSchema = Schema.Union([SimpleParameterSchema, NonAsciiStringæøåÆøÅöôêÊ字符串Schema]).check(Schema.makeFilter(Schema.is(Schema.Struct({
  baz: Schema.Union([Schema.Number.check(Schema.isInt(), Schema.isGreaterThanOrEqualTo(0)).annotate({ format: 'uint16' }), Schema.Null]).annotate({ format: 'uint16' }),
  qux: Schema.Number.check(Schema.isInt(), Schema.isGreaterThanOrEqualTo(0)).annotate({ format: 'uint8' })
})), { expected: 'a value matching this allOf member' }));

/**
 * Parameter with illegal characters
 */
export const XFooBarSchema = ModelWithStringSchema.annotate({ description: 'Parameter with illegal characters' });

/**
 * A reusable request body
 */
export const SimpleRequestBodySchema = ModelWithStringSchema.annotate({ description: 'A reusable request body' });

/**
 * A reusable request body
 */
export const SimpleFormDataSchema = ModelWithStringSchema.annotate({ description: 'A reusable request body' });

export const ExportDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const PatchApiVbyApiVersionNoTagDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

const ModelWithArrayReadOnlyAndWriteOnlyWritableFileInputSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.Array(ModelWithReadOnlyAndWriteOnlyWritableSchema)),
  propWithFile: Schema.optionalKey(Schema.Array(Schema.instanceOf(globalThis.Blob))),
  propWithNumber: Schema.optionalKey(Schema.Array(Schema.Number.check(Schema.isFinite())))
}).annotate({ description: 'This is a model with one property containing an array' });

export const ImportDataSchema = Schema.Struct({
  body: Schema.Union([ModelWithReadOnlyAndWriteOnlyWritableSchema, ModelWithArrayReadOnlyAndWriteOnlyWritableFileInputSchema]),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const ImportResponseSchema = Schema.Union([ModelFromZendeskSchema.annotate({ description: 'Success' }), ModelWithReadOnlyAndWriteOnlySchema.annotate({ description: 'Default success response' })]);

export const FooWowDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const ApiVVersionODataControllerCountDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * Success
 */
export const ApiVVersionODataControllerCountResponseSchema = ModelFromZendeskSchema.annotate({ description: 'Success' });

export const GetApiVbyApiVersionSimpleOperationDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.Struct({
    foo_param: Schema.Union([Schema.String, Schema.String.check(Schema.isUUID()).annotate({ format: 'uuid' })]).annotate({ description: 'foo in method' })
  }),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * Response is a simple number
 */
export const GetApiVbyApiVersionSimpleOperationResponseSchema = Schema.Number.check(Schema.isFinite()).annotate({ description: 'Response is a simple number' });

export const DeleteCallWithoutParametersAndResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const GetCallWithoutParametersAndResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const HeadCallWithoutParametersAndResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const OptionsCallWithoutParametersAndResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const PatchCallWithoutParametersAndResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const PostCallWithoutParametersAndResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const PutCallWithoutParametersAndResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const DeleteFooDataSchema2 = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.Struct({
    foo_param: Schema.String.annotate({ description: 'foo in method' }),
    BarParam: Schema.String.annotate({ description: 'bar in method' })
  }),
  query: Schema.optionalKey(Schema.Never),
  headers: Schema.Struct({
    'x-Foo-Bar': ModelWithStringSchema.annotate({ description: 'Parameter with illegal characters' })
  })
});

export const CallWithDescriptionsDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Struct({
    parameterWithBreaks: Schema.optionalKey(Schema.String.annotate({ description: 'Testing multiline comments in string: First line\nSecond line\n\nFourth line' })),
    parameterWithBackticks: Schema.optionalKey(Schema.String.annotate({ description: 'Testing backticks in string: `backticks` and ```multiple backticks``` should work' })),
    parameterWithSlashes: Schema.optionalKey(Schema.String.annotate({ description: 'Testing slashes in string: \\backwards\\\\\\ and /forwards/// should work' })),
    parameterWithExpressionPlaceholders: Schema.optionalKey(Schema.String.annotate({ description: 'Testing expression placeholders in string: ${expression} should work' })),
    parameterWithQuotes: Schema.optionalKey(Schema.String.annotate({ description: 'Testing quotes in string: \'single quote\'\'\' and "double quotes""" should work' })),
    parameterWithReservedCharacters: Schema.optionalKey(Schema.String.annotate({ description: 'Testing reserved characters in string: /* inline */ and /** inline **/ should work' }))
  }))
});

export const DeprecatedCallDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never),
  headers: Schema.Struct({
    parameter: Schema.Union([DeprecatedModelSchema, Schema.Null]).annotate({ description: 'This parameter is deprecated' })
  })
});

export const CallWithParametersDataSchema = Schema.Struct({
  body: Schema.Union([Schema.Record(Schema.String, Schema.Unknown), Schema.Null]).annotate({ description: 'This is the parameter that goes into the body' }),
  path: Schema.Struct({
    parameterPath: Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is the parameter that goes into the path' }),
    'api-version': Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'api-version should be required in standalone clients' })
  }),
  query: Schema.Struct({
    foo_ref_enum: Schema.optionalKey(ModelWithNestedArrayEnumsDataFooSchema),
    foo_all_of_enum: ModelWithNestedArrayEnumsDataFooSchema,
    cursor: Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is the parameter that goes into the query params' })
  }),
  headers: Schema.Struct({
    parameterHeader: Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is the parameter that goes into the header' })
  })
});

export const CallWithWeirdParameterNamesDataSchema = Schema.Struct({
  body: Schema.Union([ModelWithStringSchema, Schema.Null]).annotate({ description: 'This is the parameter that goes into the body' }),
  path: Schema.Struct({
    'parameter.path.1': Schema.optionalKey(Schema.String.annotate({ description: 'This is the parameter that goes into the path' })),
    'parameter-path-2': Schema.optionalKey(Schema.String.annotate({ description: 'This is the parameter that goes into the path' })),
    'PARAMETER-PATH-3': Schema.optionalKey(Schema.String.annotate({ description: 'This is the parameter that goes into the path' })),
    'api-version': Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'api-version should be required in standalone clients' })
  }),
  query: Schema.Struct({
    default: Schema.optionalKey(Schema.String.annotate({ description: 'This is the parameter with a reserved keyword' })),
    'parameter-query': Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is the parameter that goes into the request query params' })
  }),
  headers: Schema.Struct({
    'parameter.header': Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is the parameter that goes into the request header' })
  })
});

export const GetCallWithOptionalParamDataSchema = Schema.Struct({
  body: ModelWithOneOfEnumSchema.annotate({ description: 'This is a required parameter' }),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Struct({
    page: Schema.optionalKey(Schema.Number.check(Schema.isFinite()).annotate({ description: 'This is an optional parameter' }))
  }))
});

export const PostCallWithOptionalParamDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Struct({
    offset: Schema.optionalKey(Schema.Union([Schema.Number.check(Schema.isFinite()), Schema.Null]))
  }).annotate({ description: 'This is an optional parameter' })),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.Struct({
    parameter: PageableSchema.annotate({ description: 'This is a required parameter' })
  })
});

export const PostCallWithOptionalParamResponseSchema = Schema.Union([Schema.Number.check(Schema.isFinite()).annotate({ description: 'Response is a simple number' }), Schema.Void.annotate({ description: 'Success' })]);

export const PostApiVbyApiVersionRequestBodyDataSchema = Schema.Struct({
  body: Schema.optionalKey(SimpleRequestBodySchema.annotate({ description: 'A reusable request body' })),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Struct({
    parameter: Schema.optionalKey(Schema.String.annotate({ description: 'This is a reusable parameter' }))
  }))
});

export const PostApiVbyApiVersionFormDataDataSchema = Schema.Struct({
  body: Schema.optionalKey(SimpleFormDataSchema.annotate({ description: 'A reusable request body' })),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Struct({
    parameter: Schema.optionalKey(Schema.String.annotate({ description: 'This is a reusable parameter' }))
  }))
});

export const CallWithDefaultParametersDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Struct({
    parameterString: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a simple string with default value' })),
    parameterNumber: Schema.optionalKey(Schema.Union([Schema.Number.check(Schema.isFinite()), Schema.Null]).annotate({ description: 'This is a simple number with default value' })),
    parameterBoolean: Schema.optionalKey(Schema.Union([Schema.Boolean, Schema.Null]).annotate({ description: 'This is a simple boolean with default value' })),
    parameterEnum: Schema.optionalKey(Schema.Union([
      Schema.Literal('Success'),
      Schema.Literal('Warning'),
      Schema.Literal('Error')
    ]).annotate({ description: 'This is a simple enum with default value' })),
    parameterModel: Schema.optionalKey(Schema.Union([ModelWithStringSchema, Schema.Null]).annotate({ description: 'This is a simple model with default value' }))
  }))
});

export const CallWithDefaultOptionalParametersDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Struct({
    parameterString: Schema.optionalKey(Schema.String.annotate({ description: 'This is a simple string that is optional with default value' })),
    parameterNumber: Schema.optionalKey(Schema.Number.check(Schema.isFinite()).annotate({ description: 'This is a simple number that is optional with default value' })),
    parameterBoolean: Schema.optionalKey(Schema.Boolean.annotate({ description: 'This is a simple boolean that is optional with default value' })),
    parameterEnum: Schema.optionalKey(Schema.Union([
      Schema.Literal('Success'),
      Schema.Literal('Warning'),
      Schema.Literal('Error')
    ]).annotate({ description: 'This is a simple enum that is optional with default value' })),
    parameterModel: Schema.optionalKey(ModelWithStringSchema.annotate({ description: 'This is a simple model that is optional with default value' }))
  }))
});

export const CallToTestOrderOfParamsDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.Struct({
    parameterOptionalStringWithDefault: Schema.optionalKey(Schema.String.annotate({ description: 'This is a optional string with default' })),
    parameterOptionalStringWithEmptyDefault: Schema.optionalKey(Schema.String.annotate({ description: 'This is a optional string with empty default' })),
    parameterOptionalStringWithNoDefault: Schema.optionalKey(Schema.String.annotate({ description: 'This is a optional string with no default' })),
    parameterStringWithDefault: Schema.String.annotate({ description: 'This is a string with default' }),
    parameterStringWithEmptyDefault: Schema.String.annotate({ description: 'This is a string with empty default' }),
    parameterStringWithNoDefault: Schema.String.annotate({ description: 'This is a string with no default' }),
    parameterStringNullableWithNoDefault: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a string that can be null with no default' })),
    parameterStringNullableWithDefault: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a string that can be null with default' }))
  })
});

export const DuplicateNameDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const DuplicateName2DataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const DuplicateName3DataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const DuplicateName4DataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const CallWithNoContentResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * Success
 */
export const CallWithNoContentResponseResponseSchema = Schema.Void.annotate({ description: 'Success' });

export const CallWithResponseAndNoContentResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const CallWithResponseAndNoContentResponseResponseSchema = Schema.Union([Schema.Number.check(Schema.isFinite()).annotate({ description: 'Response is a simple number' }), Schema.Void.annotate({ description: 'Success' })]);

export const DummyADataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const DummyAResponseSchema = _400Schema;

export const DummyBDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * Success
 */
export const DummyBResponseSchema = Schema.Void.annotate({ description: 'Success' });

export const CallWithResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const CallWithResponseResponseSchema = ImportSchema;

export const CallWithDuplicateResponsesDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const CallWithDuplicateResponsesResponseSchema = Schema.Union([Schema.Struct({
    prop: Schema.optionalKey(Schema.Never)
  }).annotate({ description: 'Message for 200 response' }), ModelWithStringSchema.annotate({ description: 'Message for 201 response' })]);

export const CallWithResponsesDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const CallWithResponsesResponseSchema = Schema.Union([
  Schema.Struct({
    '@namespace.string': Schema.optionalKey(Schema.String),
    '@namespace.integer': Schema.optionalKey(Schema.Number.check(Schema.isInt())),
    value: Schema.optionalKey(Schema.Array(ModelWithStringSchema))
  }).annotate({ description: 'Message for 200 response' }),
  ModelThatExtendsSchema.annotate({ description: 'Message for 201 response' }),
  ModelThatExtendsExtendsSchema.annotate({ description: 'Message for 202 response' })
]);

export const CollectionFormatDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.Struct({
    parameterArrayCSV: Schema.Union([Schema.Array(Schema.String), Schema.Null]).annotate({ description: 'This is an array parameter that is sent as csv format (comma-separated values)' }),
    parameterArraySSV: Schema.Union([Schema.Array(Schema.String), Schema.Null]).annotate({ description: 'This is an array parameter that is sent as ssv format (space-separated values)' }),
    parameterArrayTSV: Schema.Union([Schema.Array(Schema.String), Schema.Null]).annotate({ description: 'This is an array parameter that is sent as tsv format (tab-separated values)' }),
    parameterArrayPipes: Schema.Union([Schema.Array(Schema.String), Schema.Null]).annotate({ description: 'This is an array parameter that is sent as pipes format (pipe-separated values)' }),
    parameterArrayMulti: Schema.Union([Schema.Array(Schema.String), Schema.Null]).annotate({ description: 'This is an array parameter that is sent as multi format (multiple parameter instances)' })
  })
});

export const TypesDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Struct({
    id: Schema.optionalKey(Schema.Number.check(Schema.isInt()).annotate({ description: 'This is a number parameter', format: 'int32' }))
  })),
  query: Schema.Struct({
    parameterNumber: Schema.Number.check(Schema.isFinite()).annotate({ description: 'This is a number parameter' }),
    parameterString: Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a string parameter' }),
    parameterBoolean: Schema.Union([Schema.Boolean, Schema.Null]).annotate({ description: 'This is a boolean parameter' }),
    parameterObject: Schema.Union([Schema.Record(Schema.String, Schema.Unknown), Schema.Null]).annotate({ description: 'This is an object parameter' }),
    parameterArray: Schema.Union([Schema.Array(Schema.String), Schema.Null]).annotate({ description: 'This is an array parameter' }),
    parameterDictionary: Schema.Union([Schema.Record(Schema.String, Schema.Unknown), Schema.Null]).annotate({ description: 'This is a dictionary parameter' }),
    parameterEnum: Schema.Union([
      Schema.Literal('Success'),
      Schema.Literal('Warning'),
      Schema.Literal('Error'),
      Schema.Null
    ]).annotate({ description: 'This is an enum parameter' })
  })
});

export const TypesResponseSchema = Schema.Union([
  Schema.Number.check(Schema.isFinite()).annotate({ description: 'Response is a simple number' }),
  Schema.String.annotate({ description: 'Response is a simple string' }),
  Schema.Boolean.annotate({ description: 'Response is a simple boolean' }),
  Schema.Record(Schema.String, Schema.Unknown).annotate({ description: 'Response is a simple object' })
]);

export const UploadFileDataSchema = Schema.Struct({
  body: Schema.instanceOf(globalThis.Blob),
  path: Schema.Struct({
    'api-version': Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'api-version should be required in standalone clients' })
  }),
  query: Schema.optionalKey(Schema.Never)
});

export const UploadFileResponseSchema = Schema.Boolean;

export const FileResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.Struct({
    id: Schema.String,
    'api-version': Schema.String.annotate({ description: 'api-version should be required in standalone clients' })
  }),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * Success
 */
export const FileResponseResponseSchema = Schema.Uint8Array.annotate({ description: 'Success' });

export const ComplexTypesDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.Struct({
    parameterObject: Schema.Struct({
      first: Schema.optionalKey(Schema.Struct({
        second: Schema.optionalKey(Schema.Struct({
          third: Schema.optionalKey(Schema.String)
        }))
      }))
    }).annotate({ description: 'Parameter containing object' }),
    parameterReference: ModelWithStringSchema.annotate({ description: 'Parameter containing reference' })
  })
});

/**
 * Successful response
 */
export const ComplexTypesResponseSchema = Schema.Array(ModelWithStringSchema).annotate({ description: 'Successful response' });

export const MultipartResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * OK
 */
export const MultipartResponseResponseSchema = Schema.Struct({
  file: Schema.optionalKey(Schema.Uint8Array),
  metadata: Schema.optionalKey(Schema.Struct({
    foo: Schema.optionalKey(Schema.String),
    bar: Schema.optionalKey(Schema.String)
  }))
}).annotate({ description: 'OK' });

export const MultipartRequestDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Struct({
    content: Schema.optionalKey(Schema.instanceOf(globalThis.Blob)),
    data: Schema.optionalKey(Schema.Union([ModelWithStringSchema, Schema.Null]))
  })),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

const ModelWithArrayFileInputSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.Array(ModelWithStringSchema)),
  propWithFile: Schema.optionalKey(Schema.Array(Schema.instanceOf(globalThis.Blob))),
  propWithNumber: Schema.optionalKey(Schema.Array(Schema.Number.check(Schema.isFinite())))
}).annotate({ description: 'This is a model with one property containing an array' });

export const ComplexParamsDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Struct({
    key: Schema.Union([Schema.String.check(Schema.isMaxLength(64), Schema.isPattern(new RegExp('^[a-zA-Z0-9_]*$'))), Schema.Null]),
    name: Schema.Union([Schema.String.check(Schema.isMaxLength(255)), Schema.Null]),
    enabled: Schema.optionalKey(Schema.Boolean),
    type: Schema.Union([
      Schema.Literal('Monkey'),
      Schema.Literal('Horse'),
      Schema.Literal('Bird')
    ]),
    listOfModels: Schema.optionalKey(Schema.Union([Schema.Array(ModelWithStringSchema), Schema.Null])),
    listOfStrings: Schema.optionalKey(Schema.Union([Schema.Array(Schema.String), Schema.Null])),
    parameters: Schema.Union([
      ModelWithStringSchema,
      ModelWithEnumSchema,
      ModelWithArrayFileInputSchema,
      ModelWithDictionarySchema
    ]),
    user: Schema.optionalKey(Schema.Struct({
      id: Schema.optionalKey(Schema.Number.check(Schema.isInt()).annotate({ format: 'int32' })),
      name: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null]))
    }))
  })),
  path: Schema.Struct({
    id: Schema.Number.check(Schema.isInt()).annotate({ format: 'int32' }),
    'api-version': Schema.String.annotate({ description: 'api-version should be required in standalone clients' })
  }),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * Success
 */
export const ComplexParamsResponseSchema = ModelWithStringSchema.annotate({ description: 'Success' });

export const CallWithResultFromHeaderDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const TestErrorCodeDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.Struct({
    status: Schema.Number.check(Schema.isInt()).annotate({ description: 'Status code to return' })
  })
});

export const NonAsciiæøåÆøÅöôêÊ字符串DataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.Struct({
    nonAsciiParamæøåÆØÅöôêÊ: Schema.Number.check(Schema.isInt()).annotate({ description: 'Dummy input param' })
  })
});

/**
 * Successful response
 */
export const NonAsciiæøåÆøÅöôêÊ字符串ResponseSchema = Schema.Array(NonAsciiStringæøåÆøÅöôêÊ字符串Schema).annotate({ description: 'Successful response' });

export const PutWithFormUrlEncodedDataSchema = Schema.Struct({
  body: ArrayWithStringsSchema,
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const ImportPayloadSchema = Schema.Union([ModelWithReadOnlyAndWriteOnlyWritableSchema, ModelWithArrayReadOnlyAndWriteOnlyWritableSchema]);

/**
 * Success
 */
export const ImportResponse200Schema = ModelFromZendeskSchema.annotate({ description: 'Success' });

export const GetApiVbyApiVersionSimpleOperationPathParamsSchema = Schema.Struct({
  foo_param: Schema.Union([Schema.String, Schema.String.check(Schema.isUUID()).annotate({ format: 'uuid' })]).annotate({ description: 'foo in method' })
});

/**
 * Response is a simple number
 */
export const GetApiVbyApiVersionSimpleOperationResponse200Schema = Schema.Number.check(Schema.isFinite()).annotate({ description: 'Response is a simple number' });

/**
 * Success
 */
export const ApiVVersionODataControllerCountResponse200Schema = ModelFromZendeskSchema.annotate({ description: 'Success' });

export const DeleteFooPathParamsSchema = Schema.Struct({
  foo_param: Schema.String.annotate({ description: 'foo in method' }),
  BarParam: Schema.String.annotate({ description: 'bar in method' })
});

export const DeleteFooHeadersSchema = Schema.Struct({
  'x-Foo-Bar': ModelWithStringSchema.annotate({ description: 'Parameter with illegal characters' })
});

export const CallWithParametersPathParamsSchema = Schema.Struct({
  parameterPath: Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is the parameter that goes into the path' }),
  api_version: Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'api-version should be required in standalone clients' })
});

export const CallWithParametersQuerySchema = Schema.Struct({
  foo_ref_enum: Schema.optionalKey(ModelWithNestedArrayEnumsDataFooSchema),
  foo_all_of_enum: ModelWithNestedArrayEnumsDataFooSchema,
  cursor: Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is the parameter that goes into the query params' })
});

export const CallWithParametersHeadersSchema = Schema.Struct({
  parameterHeader: Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is the parameter that goes into the header' })
});

/**
 * This is the parameter that goes into the body
 */
export const CallWithParametersPayloadSchema = Schema.Union([Schema.Record(Schema.String, Schema.Unknown), Schema.Null]).annotate({ description: 'This is the parameter that goes into the body' });

export const CallWithWeirdParameterNamesPathParamsSchema = Schema.Struct({
  parameter_path_1: Schema.optionalKey(Schema.String.annotate({ description: 'This is the parameter that goes into the path' })),
  parameter_path_2: Schema.optionalKey(Schema.String.annotate({ description: 'This is the parameter that goes into the path' })),
  PARAMETER_PATH_3: Schema.optionalKey(Schema.String.annotate({ description: 'This is the parameter that goes into the path' })),
  api_version: Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'api-version should be required in standalone clients' })
});

export const CallWithWeirdParameterNamesQuerySchema = Schema.Struct({
  default: Schema.optionalKey(Schema.String.annotate({ description: 'This is the parameter with a reserved keyword' })),
  'parameter-query': Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is the parameter that goes into the request query params' })
});

export const CallWithWeirdParameterNamesHeadersSchema = Schema.Struct({
  'parameter.header': Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is the parameter that goes into the request header' })
});

/**
 * This is the parameter that goes into the body
 */
export const CallWithWeirdParameterNamesPayloadSchema = Schema.Union([ModelWithStringSchema, Schema.Null]).annotate({ description: 'This is the parameter that goes into the body' });

export const GetCallWithOptionalParamQuerySchema = Schema.Struct({
  page: Schema.optionalKey(Schema.Number.check(Schema.isFinite()).annotate({ description: 'This is an optional parameter' }))
});

export const PostCallWithOptionalParamQuerySchema = Schema.Struct({
  parameter: PageableSchema.annotate({ description: 'This is a required parameter' })
});

/**
 * This is an optional parameter
 */
export const PostCallWithOptionalParamPayloadSchema = Schema.Struct({
  offset: Schema.optionalKey(Schema.Union([Schema.Number.check(Schema.isFinite()), Schema.Null]))
}).annotate({ description: 'This is an optional parameter' });

/**
 * Response is a simple number
 */
export const PostCallWithOptionalParamResponse200Schema = Schema.Number.check(Schema.isFinite()).annotate({ description: 'Response is a simple number' });

export const CallWithDescriptionsQuerySchema = Schema.Struct({
  parameterWithBreaks: Schema.optionalKey(Schema.String.annotate({ description: 'Testing multiline comments in string: First line\nSecond line\n\nFourth line' })),
  parameterWithBackticks: Schema.optionalKey(Schema.String.annotate({ description: 'Testing backticks in string: `backticks` and ```multiple backticks``` should work' })),
  parameterWithSlashes: Schema.optionalKey(Schema.String.annotate({ description: 'Testing slashes in string: \\backwards\\\\\\ and /forwards/// should work' })),
  parameterWithExpressionPlaceholders: Schema.optionalKey(Schema.String.annotate({ description: 'Testing expression placeholders in string: ${expression} should work' })),
  parameterWithQuotes: Schema.optionalKey(Schema.String.annotate({ description: 'Testing quotes in string: \'single quote\'\'\' and "double quotes""" should work' })),
  parameterWithReservedCharacters: Schema.optionalKey(Schema.String.annotate({ description: 'Testing reserved characters in string: /* inline */ and /** inline **/ should work' }))
});

export const DeprecatedCallHeadersSchema = Schema.Struct({
  parameter: Schema.Union([DeprecatedModelSchema, Schema.Null]).annotate({ description: 'This parameter is deprecated' })
});

export const PostApiVbyApiVersionRequestBodyQuerySchema = Schema.Struct({
  parameter: Schema.optionalKey(Schema.String.annotate({ description: 'This is a reusable parameter' }))
});

/**
 * A reusable request body
 */
export const PostApiVbyApiVersionRequestBodyPayloadSchema = SimpleRequestBodySchema.annotate({ description: 'A reusable request body' });

export const PostApiVbyApiVersionFormDataQuerySchema = Schema.Struct({
  parameter: Schema.optionalKey(Schema.String.annotate({ description: 'This is a reusable parameter' }))
});

/**
 * A reusable request body
 */
export const PostApiVbyApiVersionFormDataPayloadSchema = SimpleFormDataSchema.annotate({ description: 'A reusable request body' });

export const CallWithDefaultParametersQuerySchema = Schema.Struct({
  parameterString: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a simple string with default value' })),
  parameterNumber: Schema.optionalKey(Schema.Union([Schema.Number.check(Schema.isFinite()), Schema.Null]).annotate({ description: 'This is a simple number with default value' })),
  parameterBoolean: Schema.optionalKey(Schema.Union([Schema.Boolean, Schema.Null]).annotate({ description: 'This is a simple boolean with default value' })),
  parameterEnum: Schema.optionalKey(Schema.Union([
    Schema.Literal('Success'),
    Schema.Literal('Warning'),
    Schema.Literal('Error')
  ]).annotate({ description: 'This is a simple enum with default value' })),
  parameterModel: Schema.optionalKey(Schema.Union([ModelWithStringSchema, Schema.Null]).annotate({ description: 'This is a simple model with default value' }))
});

export const CallWithDefaultOptionalParametersQuerySchema = Schema.Struct({
  parameterString: Schema.optionalKey(Schema.String.annotate({ description: 'This is a simple string that is optional with default value' })),
  parameterNumber: Schema.optionalKey(Schema.Number.check(Schema.isFinite()).annotate({ description: 'This is a simple number that is optional with default value' })),
  parameterBoolean: Schema.optionalKey(Schema.Boolean.annotate({ description: 'This is a simple boolean that is optional with default value' })),
  parameterEnum: Schema.optionalKey(Schema.Union([
    Schema.Literal('Success'),
    Schema.Literal('Warning'),
    Schema.Literal('Error')
  ]).annotate({ description: 'This is a simple enum that is optional with default value' })),
  parameterModel: Schema.optionalKey(ModelWithStringSchema.annotate({ description: 'This is a simple model that is optional with default value' }))
});

export const CallToTestOrderOfParamsQuerySchema = Schema.Struct({
  parameterOptionalStringWithDefault: Schema.optionalKey(Schema.String.annotate({ description: 'This is a optional string with default' })),
  parameterOptionalStringWithEmptyDefault: Schema.optionalKey(Schema.String.annotate({ description: 'This is a optional string with empty default' })),
  parameterOptionalStringWithNoDefault: Schema.optionalKey(Schema.String.annotate({ description: 'This is a optional string with no default' })),
  parameterStringWithDefault: Schema.String.annotate({ description: 'This is a string with default' }),
  parameterStringWithEmptyDefault: Schema.String.annotate({ description: 'This is a string with empty default' }),
  parameterStringWithNoDefault: Schema.String.annotate({ description: 'This is a string with no default' }),
  parameterStringNullableWithNoDefault: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a string that can be null with no default' })),
  parameterStringNullableWithDefault: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a string that can be null with default' }))
});

/**
 * Response is a simple number
 */
export const CallWithResponseAndNoContentResponseResponse200Schema = Schema.Number.check(Schema.isFinite()).annotate({ description: 'Response is a simple number' });

/**
 * Message for 200 response
 */
export const CallWithDuplicateResponsesResponse200Schema = Schema.Struct({
  prop: Schema.optionalKey(Schema.Never)
}).annotate({ description: 'Message for 200 response' });

/**
 * Message for 201 response
 */
export const CallWithDuplicateResponsesResponse201Schema = ModelWithStringSchema.annotate({ description: 'Message for 201 response' });

/**
 * Message for 202 response
 */
export const CallWithDuplicateResponsesResponse202Schema = ModelWithStringSchema.annotate({ description: 'Message for 202 response' });

/**
 * Message for 500 error
 */
export const CallWithDuplicateResponsesResponse500Schema = ModelWithStringErrorSchema.annotate({ description: 'Message for 500 error' });

/**
 * Message for 501 error
 */
export const CallWithDuplicateResponsesResponse501Schema = ModelWithStringErrorSchema.annotate({ description: 'Message for 501 error' });

/**
 * Message for 502 error
 */
export const CallWithDuplicateResponsesResponse502Schema = ModelWithStringErrorSchema.annotate({ description: 'Message for 502 error' });

/**
 * Message for 200 response
 */
export const CallWithResponsesResponse200Schema = Schema.Struct({
  '@namespace.string': Schema.optionalKey(Schema.String),
  '@namespace.integer': Schema.optionalKey(Schema.Number.check(Schema.isInt())),
  value: Schema.optionalKey(Schema.Array(ModelWithStringSchema))
}).annotate({ description: 'Message for 200 response' });

/**
 * Message for 201 response
 */
export const CallWithResponsesResponse201Schema = ModelThatExtendsSchema.annotate({ description: 'Message for 201 response' });

/**
 * Message for 202 response
 */
export const CallWithResponsesResponse202Schema = ModelThatExtendsExtendsSchema.annotate({ description: 'Message for 202 response' });

/**
 * Message for 500 error
 */
export const CallWithResponsesResponse500Schema = ModelWithStringErrorSchema.annotate({ description: 'Message for 500 error' });

/**
 * Message for 501 error
 */
export const CallWithResponsesResponse501Schema = ModelWithStringErrorSchema.annotate({ description: 'Message for 501 error' });

/**
 * Message for 502 error
 */
export const CallWithResponsesResponse502Schema = ModelWithStringErrorSchema.annotate({ description: 'Message for 502 error' });

export const DummyAResponse200Schema = _400Schema;

export const CollectionFormatQuerySchema = Schema.Struct({
  parameterArrayCSV: Schema.Union([Schema.Array(Schema.String), Schema.Null]).annotate({ description: 'This is an array parameter that is sent as csv format (comma-separated values)' }),
  parameterArraySSV: Schema.Union([Schema.Array(Schema.String), Schema.Null]).annotate({ description: 'This is an array parameter that is sent as ssv format (space-separated values)' }),
  parameterArrayTSV: Schema.Union([Schema.Array(Schema.String), Schema.Null]).annotate({ description: 'This is an array parameter that is sent as tsv format (tab-separated values)' }),
  parameterArrayPipes: Schema.Union([Schema.Array(Schema.String), Schema.Null]).annotate({ description: 'This is an array parameter that is sent as pipes format (pipe-separated values)' }),
  parameterArrayMulti: Schema.Union([Schema.Array(Schema.String), Schema.Null]).annotate({ description: 'This is an array parameter that is sent as multi format (multiple parameter instances)' })
});

export const TypesPathParamsSchema = Schema.Struct({
  id: Schema.optionalKey(Schema.Number.check(Schema.isInt()).annotate({ description: 'This is a number parameter', format: 'int32' }))
});

export const TypesQuerySchema = Schema.Struct({
  parameterNumber: Schema.Number.check(Schema.isFinite()).annotate({ description: 'This is a number parameter' }),
  parameterString: Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a string parameter' }),
  parameterBoolean: Schema.Union([Schema.Boolean, Schema.Null]).annotate({ description: 'This is a boolean parameter' }),
  parameterObject: Schema.Union([Schema.Record(Schema.String, Schema.Unknown), Schema.Null]).annotate({ description: 'This is an object parameter' }),
  parameterArray: Schema.Union([Schema.Array(Schema.String), Schema.Null]).annotate({ description: 'This is an array parameter' }),
  parameterDictionary: Schema.Union([Schema.Record(Schema.String, Schema.Unknown), Schema.Null]).annotate({ description: 'This is a dictionary parameter' }),
  parameterEnum: Schema.Union([
    Schema.Literal('Success'),
    Schema.Literal('Warning'),
    Schema.Literal('Error'),
    Schema.Null
  ]).annotate({ description: 'This is an enum parameter' })
});

/**
 * Response is a simple number
 */
export const TypesResponse200Schema = Schema.Number.check(Schema.isFinite()).annotate({ description: 'Response is a simple number' });

/**
 * Response is a simple string
 */
export const TypesResponse201Schema = Schema.String.annotate({ description: 'Response is a simple string' });

/**
 * Response is a simple boolean
 */
export const TypesResponse202Schema = Schema.Boolean.annotate({ description: 'Response is a simple boolean' });

/**
 * Response is a simple object
 */
export const TypesResponse203Schema = Schema.Record(Schema.String, Schema.Unknown).annotate({ description: 'Response is a simple object' });

export const UploadFilePathParamsSchema = Schema.Struct({
  api_version: Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'api-version should be required in standalone clients' })
});

export const UploadFilePayloadSchema = Schema.Uint8Array;

export const UploadFileResponse200Schema = Schema.Boolean;

export const FileResponsePathParamsSchema = Schema.Struct({
  id: Schema.String,
  api_version: Schema.String.annotate({ description: 'api-version should be required in standalone clients' })
});

/**
 * Success
 */
export const FileResponseResponse200Schema = Schema.Uint8Array.annotate({ description: 'Success' });

export const ComplexTypesQuerySchema = Schema.Struct({
  parameterObject: Schema.Struct({
    first: Schema.optionalKey(Schema.Struct({
      second: Schema.optionalKey(Schema.Struct({
        third: Schema.optionalKey(Schema.String)
      }))
    }))
  }).annotate({ description: 'Parameter containing object' }),
  parameterReference: ModelWithStringSchema.annotate({ description: 'Parameter containing reference' })
});

/**
 * Successful response
 */
export const ComplexTypesResponse200Schema = Schema.Array(ModelWithStringSchema).annotate({ description: 'Successful response' });

/**
 * 400 `server` error
 */
export const ComplexTypesResponse400Schema = Schema.Unknown.annotate({ description: '400 `server` error' });

/**
 * 500 server error
 */
export const ComplexTypesResponse500Schema = Schema.Unknown.annotate({ description: '500 server error' });

export const ComplexParamsPathParamsSchema = Schema.Struct({
  id: Schema.Number.check(Schema.isInt()).annotate({ format: 'int32' }),
  api_version: Schema.String.annotate({ description: 'api-version should be required in standalone clients' })
});

export const ComplexParamsPayloadSchema = Schema.Struct({
  key: Schema.Union([Schema.String.check(Schema.isMaxLength(64), Schema.isPattern(new RegExp('^[a-zA-Z0-9_]*$'))), Schema.Null]),
  name: Schema.Union([Schema.String.check(Schema.isMaxLength(255)), Schema.Null]),
  enabled: Schema.optionalKey(Schema.Boolean),
  type: Schema.Union([
    Schema.Literal('Monkey'),
    Schema.Literal('Horse'),
    Schema.Literal('Bird')
  ]),
  listOfModels: Schema.optionalKey(Schema.Union([Schema.Array(ModelWithStringSchema), Schema.Null])),
  listOfStrings: Schema.optionalKey(Schema.Union([Schema.Array(Schema.String), Schema.Null])),
  parameters: Schema.Union([
    ModelWithStringSchema,
    ModelWithEnumSchema,
    ModelWithArraySchema,
    ModelWithDictionarySchema
  ]),
  user: Schema.optionalKey(Schema.Struct({
    id: Schema.optionalKey(Schema.Number.check(Schema.isInt()).annotate({ format: 'int32' })),
    name: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null]))
  }))
});

/**
 * Success
 */
export const ComplexParamsResponse200Schema = ModelWithStringSchema.annotate({ description: 'Success' });

export const MultipartRequestPayloadSchema = Schema.Struct({
  content: Schema.optionalKey(Multipart.SingleFileSchema),
  data: Schema.optionalKey(Schema.Union([ModelWithStringSchema, Schema.Null]))
});

/**
 * Successful response
 */
export const CallWithResultFromHeaderResponse200Schema = Schema.Unknown.annotate({ description: 'Successful response' });

/**
 * 400 server error
 */
export const CallWithResultFromHeaderResponse400Schema = Schema.Unknown.annotate({ description: '400 server error' });

/**
 * 500 server error
 */
export const CallWithResultFromHeaderResponse500Schema = Schema.Unknown.annotate({ description: '500 server error' });

export const TestErrorCodeQuerySchema = Schema.Struct({
  status: Schema.Number.check(Schema.isInt()).annotate({ description: 'Status code to return' })
});

/**
 * Custom message: Successful response
 */
export const TestErrorCodeResponse200Schema = Schema.Unknown.annotate({ description: 'Custom message: Successful response' });

/**
 * Custom message: Internal Server Error
 */
export const TestErrorCodeResponse500Schema = Schema.Unknown.annotate({ description: 'Custom message: Internal Server Error' });

/**
 * Custom message: Not Implemented
 */
export const TestErrorCodeResponse501Schema = Schema.Unknown.annotate({ description: 'Custom message: Not Implemented' });

/**
 * Custom message: Bad Gateway
 */
export const TestErrorCodeResponse502Schema = Schema.Unknown.annotate({ description: 'Custom message: Bad Gateway' });

/**
 * Custom message: Service Unavailable
 */
export const TestErrorCodeResponse503Schema = Schema.Unknown.annotate({ description: 'Custom message: Service Unavailable' });

export const NonAsciiæøåÆøÅöôêÊ字符串QuerySchema = Schema.Struct({
  nonAsciiParamæøåÆØÅöôêÊ: Schema.Number.check(Schema.isInt()).annotate({ description: 'Dummy input param' })
});

/**
 * Successful response
 */
export const NonAsciiæøåÆøÅöôêÊ字符串Response200Schema = Schema.Array(NonAsciiStringæøåÆøÅöôêÊ字符串Schema).annotate({ description: 'Successful response' });

export const PutWithFormUrlEncodedPayloadSchema = ArrayWithStringsSchema;
