// This file is auto-generated by @hey-api/openapi-ts

import * as Schema from 'effect/Schema';

import type { ModelWithCircularReference } from './types.gen';

/**
 * Testing multiline comments in string: First line
 * Second line
 *
 * Fourth line
 */
export const CommentWithBreaksSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'Testing multiline comments in string: First line\nSecond line\n\nFourth line' });

/**
 * Testing backticks in string: `backticks` and ```multiple backticks``` should work
 */
export const CommentWithBackticksSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'Testing backticks in string: `backticks` and ```multiple backticks``` should work' });

/**
 * Testing backticks and quotes in string: `backticks`, 'quotes', "double quotes" and ```multiple backticks``` should work
 */
export const CommentWithBackticksAndQuotesSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'Testing backticks and quotes in string: `backticks`, \'quotes\', "double quotes" and ```multiple backticks``` should work' });

/**
 * Testing slashes in string: \backwards\\\ and /forwards/// should work
 */
export const CommentWithSlashesSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'Testing slashes in string: \\backwards\\\\\\ and /forwards/// should work' });

/**
 * Testing expression placeholders in string: ${expression} should work
 */
export const CommentWithExpressionPlaceholdersSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'Testing expression placeholders in string: ${expression} should work' });

/**
 * Testing quotes in string: 'single quote''' and "double quotes""" should work
 */
export const CommentWithQuotesSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'Testing quotes in string: \'single quote\'\'\' and "double quotes""" should work' });

/**
 * Testing reserved characters in string: * inline * and ** inline ** should work
 */
export const CommentWithReservedCharactersSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'Testing reserved characters in string: /* inline */ and /** inline **/ should work' });

/**
 * This is a simple number
 */
export const SimpleIntegerSchema = Schema.Number.check(Schema.isInt()).annotate({ description: 'This is a simple number' });

/**
 * This is a simple boolean
 */
export const SimpleBooleanSchema = Schema.Boolean.annotate({ description: 'This is a simple boolean' });

/**
 * This is a simple string
 */
export const SimpleStringSchema = Schema.String.annotate({ description: 'This is a simple string' });

/**
 * A string with non-ascii (unicode) characters valid in typescript identifiers (æøåÆØÅöÔèÈ字符串)
 */
export const NonAsciiStringæøåÆøÅöôêÊ字符串Schema = Schema.String.annotate({ description: 'A string with non-ascii (unicode) characters valid in typescript identifiers (æøåÆØÅöÔèÈ字符串)' });

/**
 * This is a simple file
 */
export const SimpleFileSchema = Schema.Uint8Array.annotate({ description: 'This is a simple file' });

/**
 * This is a simple string
 */
export const SimpleStringWithPatternSchema = Schema.String.check(Schema.isMaxLength(64), Schema.isPattern(new RegExp('^[a-zA-Z0-9_]*$'))).annotate({ description: 'This is a simple string' });

/**
 * This is a simple enum with strings
 */
export const EnumWithStringsSchema = Schema.Union([
  Schema.Literal('Success'),
  Schema.Literal('Warning'),
  Schema.Literal('Error'),
  Schema.Literal('\'Single Quote\''),
  Schema.Literal('"Double Quotes"'),
  Schema.Literal('Non-ascii: øæåôöØÆÅÔÖ字符串')
]).annotate({ description: 'This is a simple enum with strings' });

/**
 * This is a simple enum with numbers
 */
export const EnumWithNumbersSchema = Schema.Union([
  Schema.Literal(1).check(Schema.isFinite()),
  Schema.Literal(2).check(Schema.isFinite()),
  Schema.Literal(3).check(Schema.isFinite()),
  Schema.Literal(1.1).check(Schema.isFinite()),
  Schema.Literal(1.2).check(Schema.isFinite()),
  Schema.Literal(1.3).check(Schema.isFinite()),
  Schema.Literal(100).check(Schema.isFinite()),
  Schema.Literal(200).check(Schema.isFinite()),
  Schema.Literal(300).check(Schema.isFinite()),
  Schema.Literal(-100).check(Schema.isFinite()),
  Schema.Literal(-200).check(Schema.isFinite()),
  Schema.Literal(-300).check(Schema.isFinite()),
  Schema.Literal(-1.1).check(Schema.isFinite()),
  Schema.Literal(-1.2).check(Schema.isFinite()),
  Schema.Literal(-1.3).check(Schema.isFinite())
]).check(Schema.isFinite()).annotate({ description: 'This is a simple enum with numbers' });

/**
 * Success=1,Warning=2,Error=3
 */
export const EnumFromDescriptionSchema = Schema.Number.check(Schema.isFinite()).annotate({ description: 'Success=1,Warning=2,Error=3' });

/**
 * This is a simple enum with numbers
 */
export const EnumWithExtensionsSchema = Schema.Union([
  Schema.Literal(200).check(Schema.isFinite()).annotate({ title: 'CUSTOM_SUCCESS', description: 'Used when the status of something is successful' }),
  Schema.Literal(400).check(Schema.isFinite()).annotate({ title: 'CUSTOM_WARNING', description: 'Used when the status of something has a warning' }),
  Schema.Literal(500).check(Schema.isFinite()).annotate({ title: 'CUSTOM_ERROR', description: 'Used when the status of something has an error' })
]).check(Schema.isFinite()).annotate({ description: 'This is a simple enum with numbers' });

/**
 * This is a simple array with numbers
 */
export const ArrayWithNumbersSchema = Schema.Array(Schema.Number.check(Schema.isInt())).annotate({ description: 'This is a simple array with numbers' });

/**
 * This is a simple array with booleans
 */
export const ArrayWithBooleansSchema = Schema.Array(Schema.Boolean).annotate({ description: 'This is a simple array with booleans' });

/**
 * This is a simple array with strings
 */
export const ArrayWithStringsSchema = Schema.Array(Schema.String).annotate({ description: 'This is a simple array with strings' });

/**
 * This is a simple array with properties
 */
export const ArrayWithPropertiesSchema = Schema.Array(Schema.Struct({
  foo: Schema.optionalKey(Schema.String),
  bar: Schema.optionalKey(Schema.String)
})).annotate({ description: 'This is a simple array with properties' });

/**
 * This is a string dictionary
 */
export const DictionaryWithStringSchema = Schema.Record(Schema.String, Schema.String).annotate({ description: 'This is a string dictionary' });

/**
 * This is a string dictionary
 */
export const DictionaryWithDictionarySchema = Schema.Record(Schema.String, Schema.Record(Schema.String, Schema.String)).annotate({ description: 'This is a string dictionary' });

/**
 * This is a complex dictionary
 */
export const DictionaryWithPropertiesSchema = Schema.Record(Schema.String, Schema.Struct({
  foo: Schema.optionalKey(Schema.String),
  bar: Schema.optionalKey(Schema.String)
})).annotate({ description: 'This is a complex dictionary' });

/**
 * This is a type-only model that defines Date as a string
 */
export const DateSchema = Schema.String.annotate({ description: 'This is a type-only model that defines Date as a string' });

/**
 * This is a model with one number property
 */
export const ModelWithIntegerSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.Number.check(Schema.isInt()).annotate({ description: 'This is a simple number property' }))
}).annotate({ description: 'This is a model with one number property' });

/**
 * This is a model with one boolean property
 */
export const ModelWithBooleanSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.Boolean.annotate({ description: 'This is a simple boolean property' }))
}).annotate({ description: 'This is a model with one boolean property' });

/**
 * This is a model with one string property
 */
export const ModelWithStringSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.String.annotate({ description: 'This is a simple string property' }))
}).annotate({ description: 'This is a model with one string property' });

export const SimpleReferenceSchema = ModelWithStringSchema;

/**
 * This is a simple array with references
 */
export const ArrayWithReferencesSchema = Schema.Array(ModelWithStringSchema).annotate({ description: 'This is a simple array with references' });

/**
 * This is a simple array containing an array
 */
export const ArrayWithArraySchema = Schema.Array(Schema.Array(ModelWithStringSchema)).annotate({ description: 'This is a simple array containing an array' });

/**
 * This is a string reference
 */
export const DictionaryWithReferenceSchema = Schema.Record(Schema.String, ModelWithStringSchema).annotate({ description: 'This is a string reference' });

/**
 * This is a complex dictionary
 */
export const DictionaryWithArraySchema = Schema.Record(Schema.String, Schema.Array(ModelWithStringSchema)).annotate({ description: 'This is a complex dictionary' });

/**
 * This is a model with one string property
 */
export const ModelWithStringErrorSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.String.annotate({ description: 'This is a simple string property' }))
}).annotate({ description: 'This is a model with one string property' });

/**
 * This is a model with one string property
 */
export const ModelWithNullableStringSchema = Schema.Struct({
  nullableProp: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a simple string property' })),
  nullableRequiredProp: Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a simple string property' })
}).annotate({ description: 'This is a model with one string property' });

/**
 * This is a model with one enum
 */
export const ModelWithEnumSchema = Schema.Struct({
  test: Schema.optionalKey(Schema.Union([
    Schema.Literal('Success'),
    Schema.Literal('Warning'),
    Schema.Literal('Error'),
    Schema.Literal('ØÆÅ字符串')
  ]).annotate({ description: 'This is a simple enum with strings' })),
  statusCode: Schema.optionalKey(Schema.Union([
    Schema.Literal('100'),
    Schema.Literal('200 FOO'),
    Schema.Literal('300 FOO_BAR'),
    Schema.Literal('400 foo-bar'),
    Schema.Literal('500 foo.bar'),
    Schema.Literal('600 foo&bar')
  ]).annotate({ description: 'These are the HTTP error code enums' })),
  bool: Schema.optionalKey(Schema.Literal(true).annotate({ description: 'Simple boolean enum' }))
}).annotate({ description: 'This is a model with one enum' });

/**
 * This is a model with one enum
 */
export const ModelWithEnumFromDescriptionSchema = Schema.Struct({
  test: Schema.optionalKey(Schema.Number.check(Schema.isInt()).annotate({ description: 'Success=1,Warning=2,Error=3' }))
}).annotate({ description: 'This is a model with one enum' });

/**
 * This is a model with nested enums
 */
export const ModelWithNestedEnumsSchema = Schema.Struct({
  dictionaryWithEnum: Schema.optionalKey(Schema.Record(Schema.String, Schema.Union([
    Schema.Literal('Success'),
    Schema.Literal('Warning'),
    Schema.Literal('Error')
  ]))),
  dictionaryWithEnumFromDescription: Schema.optionalKey(Schema.Record(Schema.String, Schema.Number.check(Schema.isInt()).annotate({ description: 'Success=1,Warning=2,Error=3' }))),
  arrayWithEnum: Schema.optionalKey(Schema.Array(Schema.Union([
    Schema.Literal('Success'),
    Schema.Literal('Warning'),
    Schema.Literal('Error')
  ]))),
  arrayWithDescription: Schema.optionalKey(Schema.Array(Schema.Number.check(Schema.isInt()).annotate({ description: 'Success=1,Warning=2,Error=3' })))
}).annotate({ description: 'This is a model with nested enums' });

/**
 * This is a model with one property containing an array
 */
export const ModelWithArraySchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.Array(ModelWithStringSchema)),
  propWithFile: Schema.optionalKey(Schema.Array(Schema.Uint8Array)),
  propWithNumber: Schema.optionalKey(Schema.Array(Schema.Number.check(Schema.isFinite())))
}).annotate({ description: 'This is a model with one property containing an array' });

/**
 * This is a model with one property containing a dictionary
 */
export const ModelWithDictionarySchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.Record(Schema.String, Schema.String))
}).annotate({ description: 'This is a model with one property containing a dictionary' });

/**
 * This is a model with one property containing a circular reference
 */
export const ModelWithCircularReferenceSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.suspend((): Schema.Codec<ModelWithCircularReference> => ModelWithCircularReferenceSchema))
}).annotate({ description: 'This is a model with one property containing a circular reference' });

/**
 * This is a model with one nested property
 */
export const ModelWithPropertiesSchema = Schema.Struct({
  required: Schema.String,
  requiredAndReadOnly: Schema.String,
  string: Schema.optionalKey(Schema.String),
  number: Schema.optionalKey(Schema.Number.check(Schema.isFinite())),
  boolean: Schema.optionalKey(Schema.Boolean),
  reference: Schema.optionalKey(ModelWithStringSchema),
  'property with space': Schema.optionalKey(Schema.String),
  default: Schema.optionalKey(Schema.String),
  try: Schema.optionalKey(Schema.String),
  '@namespace.string': Schema.optionalKey(Schema.String),
  '@namespace.integer': Schema.optionalKey(Schema.Number.check(Schema.isInt()))
}).annotate({ description: 'This is a model with one nested property' });

/**
 * This is a model with one property containing a reference
 */
export const ModelWithReferenceSchema = Schema.Struct({
  prop: Schema.optionalKey(ModelWithPropertiesSchema)
}).annotate({ description: 'This is a model with one property containing a reference' });

/**
 * This is a model with one nested property
 */
export const ModelWithNestedPropertiesSchema = Schema.Struct({
  first: Schema.Struct({
    second: Schema.Struct({
      third: Schema.String
    })
  })
}).annotate({ description: 'This is a model with one nested property' });

/**
 * This is a model with duplicated properties
 */
export const ModelWithDuplicatePropertiesSchema = Schema.Struct({
  prop: Schema.optionalKey(ModelWithStringSchema)
}).annotate({ description: 'This is a model with duplicated properties' });

/**
 * This is a model with ordered properties
 */
export const ModelWithOrderedPropertiesSchema = Schema.Struct({
  zebra: Schema.optionalKey(Schema.String),
  apple: Schema.optionalKey(Schema.String),
  hawaii: Schema.optionalKey(Schema.String)
}).annotate({ description: 'This is a model with ordered properties' });

/**
 * This is a model with duplicated imports
 */
export const ModelWithDuplicateImportsSchema = Schema.Struct({
  propA: Schema.optionalKey(ModelWithStringSchema),
  propB: Schema.optionalKey(ModelWithStringSchema),
  propC: Schema.optionalKey(ModelWithStringSchema)
}).annotate({ description: 'This is a model with duplicated imports' });

/**
 * This is a model that extends another model
 */
export const ModelThatExtendsSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.String.annotate({ description: 'This is a simple string property' })),
  propExtendsA: Schema.optionalKey(Schema.String),
  propExtendsB: Schema.optionalKey(ModelWithStringSchema)
}).annotate({ description: 'This is a model that extends another model' });

/**
 * This is a model that extends another model
 */
export const ModelThatExtendsExtendsSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.String.annotate({ description: 'This is a simple string property' })),
  propExtendsA: Schema.optionalKey(Schema.String),
  propExtendsB: Schema.optionalKey(ModelWithStringSchema),
  propExtendsC: Schema.optionalKey(Schema.String),
  propExtendsD: Schema.optionalKey(ModelWithStringSchema)
}).annotate({ description: 'This is a model that extends another model' });

export const DefaultSchema = Schema.Struct({
  name: Schema.optionalKey(Schema.String)
});

/**
 * This is a model that contains a some patterns
 */
export const ModelWithPatternSchema = Schema.Struct({
  key: Schema.String.check(Schema.isMaxLength(64), Schema.isPattern(new RegExp('^[a-zA-Z0-9_]*$'))),
  name: Schema.String.check(Schema.isMaxLength(255)),
  enabled: Schema.optionalKey(Schema.Boolean),
  modified: Schema.optionalKey(Schema.String.check(Schema.makeFilter(value => {
    if (!/^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))[tT](?:[01]\d|2[0-3]):[0-5]\d:(?:[0-5]\d|60)(?:\.\d+)?(?:[zZ]|[+-](?:[01]\d|2[0-3]):[0-5]\d)$/.test(value)) {
      return false;
    }
    if (!value.includes(':60')) {
      return true;
    }
    const parsed = new globalThis.Date(value.replace(':60', ':59'));
    if (parsed.getUTCHours() !== 23 || parsed.getUTCMinutes() !== 59) {
      return false;
    }
    return parsed.getUTCMonth() === 5 && parsed.getUTCDate() === 30 || parsed.getUTCMonth() === 11 && parsed.getUTCDate() === 31;
  }, { expected: 'an RFC 3339 date-time' })).annotate({ format: 'date-time' })),
  id: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^\\d{2}-\\d{3}-\\d{4}$')))),
  text: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^\\w+$')))),
  patternWithSingleQuotes: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^[a-zA-Z0-9\']*$')))),
  patternWithNewline: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('aaa\\nbbb')))),
  patternWithBacktick: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('aaa`bbb')))),
  patternWithUnicode: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^\\p{L}+$'))))
}).annotate({ description: 'This is a model that contains a some patterns' });

export const ParameterActivityParamsSchema = Schema.Struct({
  description: Schema.optionalKey(Schema.String),
  graduate_id: Schema.optionalKey(Schema.Number.check(Schema.isInt())),
  organization_id: Schema.optionalKey(Schema.Number.check(Schema.isInt())),
  parent_activity: Schema.optionalKey(Schema.Number.check(Schema.isInt())),
  post_id: Schema.optionalKey(Schema.Number.check(Schema.isInt()))
});

export const ResponsePostActivityResponseSchema = Schema.Struct({
  description: Schema.optionalKey(Schema.String),
  graduate_id: Schema.optionalKey(Schema.Number.check(Schema.isInt())),
  organization_id: Schema.optionalKey(Schema.Number.check(Schema.isInt())),
  parent_activity_id: Schema.optionalKey(Schema.Number.check(Schema.isInt())),
  post_id: Schema.optionalKey(Schema.Number.check(Schema.isInt()))
});

export const FailureFailureSchema = Schema.Struct({
  error: Schema.optionalKey(Schema.String),
  message: Schema.optionalKey(Schema.String),
  reference_code: Schema.optionalKey(Schema.String)
});

export const ExternalSharedModelSchema = Schema.Struct({
  id: Schema.String,
  name: Schema.optionalKey(Schema.String)
});

export const ExternalRefASchema = ExternalSharedModelSchema;

export const ExternalRefBSchema = ExternalSharedModelSchema;

/**
 * This is a model with one nested property
 */
export const ModelWithPropertiesWritableSchema = Schema.Struct({
  required: Schema.String,
  string: Schema.optionalKey(Schema.String),
  number: Schema.optionalKey(Schema.Number.check(Schema.isFinite())),
  boolean: Schema.optionalKey(Schema.Boolean),
  reference: Schema.optionalKey(ModelWithStringSchema),
  'property with space': Schema.optionalKey(Schema.String),
  default: Schema.optionalKey(Schema.String),
  try: Schema.optionalKey(Schema.String)
}).annotate({ description: 'This is a model with one nested property' });

/**
 * This is a model with one property containing a reference
 */
export const ModelWithReferenceWritableSchema = Schema.Struct({
  prop: Schema.optionalKey(ModelWithPropertiesWritableSchema)
}).annotate({ description: 'This is a model with one property containing a reference' });

/**
 * This is a model that contains a some patterns
 */
export const ModelWithPatternWritableSchema = Schema.Struct({
  key: Schema.String.check(Schema.isMaxLength(64), Schema.isPattern(new RegExp('^[a-zA-Z0-9_]*$'))),
  name: Schema.String.check(Schema.isMaxLength(255)),
  id: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^\\d{2}-\\d{3}-\\d{4}$')))),
  text: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^\\w+$')))),
  patternWithSingleQuotes: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^[a-zA-Z0-9\']*$')))),
  patternWithNewline: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('aaa\\nbbb')))),
  patternWithBacktick: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('aaa`bbb')))),
  patternWithUnicode: Schema.optionalKey(Schema.String.check(Schema.isPattern(new RegExp('^\\p{L}+$'))))
}).annotate({ description: 'This is a model that contains a some patterns' });

export const ServiceWithEmptyTagDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const PatchApiVbyApiVersionNoTagDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const FooWowDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const DeleteCallWithoutParametersAndResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const GetCallWithoutParametersAndResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const HeadCallWithoutParametersAndResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const OptionsCallWithoutParametersAndResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const PatchCallWithoutParametersAndResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const PostCallWithoutParametersAndResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const PutCallWithoutParametersAndResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const CallWithDescriptionsDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Struct({
    parameterWithBreaks: Schema.optionalKey(Schema.String.annotate({ description: 'Testing multiline comments in string: First line\nSecond line\n\nFourth line' })),
    parameterWithBackticks: Schema.optionalKey(Schema.String.annotate({ description: 'Testing backticks in string: `backticks` and ```multiple backticks``` should work' })),
    parameterWithSlashes: Schema.optionalKey(Schema.String.annotate({ description: 'Testing slashes in string: \\backwards\\\\\\ and /forwards/// should work' })),
    parameterWithExpressionPlaceholders: Schema.optionalKey(Schema.String.annotate({ description: 'Testing expression placeholders in string: ${expression} should work' })),
    parameterWithQuotes: Schema.optionalKey(Schema.String.annotate({ description: 'Testing quotes in string: \'single quote\'\'\' and "double quotes""" should work' })),
    parameterWithReservedCharacters: Schema.optionalKey(Schema.String.annotate({ description: 'Testing reserved characters in string: /* inline */ and /** inline **/ should work' }))
  }))
});

export const CallWithParametersDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.Struct({
    parameterPath: Schema.String.annotate({ description: 'This is the parameter that goes into the path' }),
    'api-version': Schema.String.annotate({ description: 'api-version should be required in standalone clients' })
  }),
  query: Schema.Struct({
    parameterQuery: Schema.String.annotate({ description: 'This is the parameter that goes into the query params' })
  }),
  headers: Schema.Struct({
    parameterHeader: Schema.String.annotate({ description: 'This is the parameter that goes into the header' })
  })
});

export const CallWithWeirdParameterNamesDataSchema = Schema.Struct({
  body: Schema.String.annotate({ description: 'This is the parameter that is sent as request body' }),
  path: Schema.Struct({
    'parameter.path.1': Schema.optionalKey(Schema.String.annotate({ description: 'This is the parameter that goes into the path' })),
    'parameter-path-2': Schema.optionalKey(Schema.String.annotate({ description: 'This is the parameter that goes into the path' })),
    'PARAMETER-PATH-3': Schema.optionalKey(Schema.String.annotate({ description: 'This is the parameter that goes into the path' })),
    'api-version': Schema.String.annotate({ description: 'api-version should be required in standalone clients' })
  }),
  query: Schema.Struct({
    default: Schema.optionalKey(Schema.String.annotate({ description: 'This is the parameter with a reserved keyword' })),
    'parameter-query': Schema.String.annotate({ description: 'This is the parameter that goes into the request query params' })
  }),
  headers: Schema.Struct({
    'parameter.header': Schema.String.annotate({ description: 'This is the parameter that goes into the request header' })
  })
});

export const CallWithDefaultParametersDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.Struct({
    parameterString: Schema.String.annotate({ description: 'This is a simple string with default value' }),
    parameterNumber: Schema.Number.check(Schema.isFinite()).annotate({ description: 'This is a simple number with default value' }),
    parameterBoolean: Schema.Boolean.annotate({ description: 'This is a simple boolean with default value' }),
    parameterEnum: Schema.Union([
      Schema.Literal('Success'),
      Schema.Literal('Warning'),
      Schema.Literal('Error')
    ]).annotate({ description: 'This is a simple enum with default value' }),
    parameterModel: Schema.Struct({
      prop: Schema.optionalKey(Schema.String.annotate({ description: 'This is a simple string property' }))
    }).annotate({ description: 'This is a model with one string property' })
  })
});

export const CallWithDefaultOptionalParametersDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Struct({
    parameterString: Schema.optionalKey(Schema.String.annotate({ description: 'This is a simple string that is optional with default value' })),
    parameterNumber: Schema.optionalKey(Schema.Number.check(Schema.isFinite()).annotate({ description: 'This is a simple number that is optional with default value' })),
    parameterBoolean: Schema.optionalKey(Schema.Boolean.annotate({ description: 'This is a simple boolean that is optional with default value' })),
    parameterEnum: Schema.optionalKey(Schema.Union([
      Schema.Literal('Success'),
      Schema.Literal('Warning'),
      Schema.Literal('Error')
    ]).annotate({ description: 'This is a simple enum that is optional with default value' }))
  }))
});

export const CallToTestOrderOfParamsDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.Struct({
    parameterOptionalStringWithDefault: Schema.optionalKey(Schema.String.annotate({ description: 'This is a optional string with default' })),
    parameterOptionalStringWithEmptyDefault: Schema.optionalKey(Schema.String.annotate({ description: 'This is a optional string with empty default' })),
    parameterOptionalStringWithNoDefault: Schema.optionalKey(Schema.String.annotate({ description: 'This is a optional string with no default' })),
    parameterStringWithDefault: Schema.String.annotate({ description: 'This is a string with default' }),
    parameterStringWithEmptyDefault: Schema.String.annotate({ description: 'This is a string with empty default' }),
    parameterStringWithNoDefault: Schema.String.annotate({ description: 'This is a string with no default' }),
    parameterStringNullableWithNoDefault: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a string that can be null with no default' })),
    parameterStringNullableWithDefault: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null]).annotate({ description: 'This is a string that can be null with default' }))
  })
});

export const DuplicateNameDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const DuplicateName2DataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const DuplicateName3DataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const DuplicateName4DataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const CallWithNoContentResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const CallWithResponseAndNoContentResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const CallWithResponseAndNoContentResponseResponseSchema = Schema.Union([Schema.Number.check(Schema.isFinite()).annotate({ description: 'Response is a simple number' }), Schema.Unknown.annotate({ description: 'Success' })]);

export const DummyADataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const DummyBDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const CallWithResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * Message for default response
 */
export const CallWithResponseResponseSchema = ModelWithStringSchema.annotate({ description: 'Message for default response' });

export const CallWithDuplicateResponsesDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * Message for 201 response
 */
export const CallWithDuplicateResponsesResponseSchema = ModelWithStringSchema.annotate({ description: 'Message for 201 response' });

export const CallWithResponsesDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const CallWithResponsesResponseSchema = Schema.Union([
  Schema.Struct({
    '@namespace.string': Schema.optionalKey(Schema.String),
    '@namespace.integer': Schema.optionalKey(Schema.Number.check(Schema.isInt())),
    value: Schema.optionalKey(Schema.Array(ModelWithStringSchema))
  }).annotate({ description: 'Message for 200 response' }),
  ModelThatExtendsSchema.annotate({ description: 'Message for 201 response' }),
  ModelThatExtendsExtendsSchema.annotate({ description: 'Message for 202 response' })
]);

export const CollectionFormatDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.Struct({
    parameterArrayCSV: Schema.Array(Schema.String).annotate({ description: 'This is an array parameter that is sent as csv format (comma-separated values)' }),
    parameterArraySSV: Schema.Array(Schema.String).annotate({ description: 'This is an array parameter that is sent as ssv format (space-separated values)' }),
    parameterArrayTSV: Schema.Array(Schema.String).annotate({ description: 'This is an array parameter that is sent as tsv format (tab-separated values)' }),
    parameterArrayPipes: Schema.Array(Schema.String).annotate({ description: 'This is an array parameter that is sent as pipes format (pipe-separated values)' }),
    parameterArrayMulti: Schema.Array(Schema.String).annotate({ description: 'This is an array parameter that is sent as multi format (multiple parameter instances)' })
  })
});

export const TypesDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Struct({
    id: Schema.optionalKey(Schema.Number.check(Schema.isInt()).annotate({ description: 'This is a number parameter', format: 'int32' }))
  })),
  query: Schema.Struct({
    parameterNumber: Schema.Number.check(Schema.isFinite()).annotate({ description: 'This is a number parameter' }),
    parameterString: Schema.String.annotate({ description: 'This is a string parameter' }),
    parameterBoolean: Schema.Boolean.annotate({ description: 'This is a boolean parameter' }),
    parameterArray: Schema.Array(Schema.String).annotate({ description: 'This is an array parameter' }),
    parameterDictionary: Schema.Record(Schema.String, Schema.Unknown).annotate({ description: 'This is a dictionary parameter' }),
    parameterEnum: Schema.Union([
      Schema.Literal('Success'),
      Schema.Literal('Warning'),
      Schema.Literal('Error')
    ]).annotate({ description: 'This is an enum parameter' })
  })
});

export const TypesResponseSchema = Schema.Union([
  Schema.Number.check(Schema.isFinite()).annotate({ description: 'Response is a simple number' }),
  Schema.String.annotate({ description: 'Response is a simple string' }),
  Schema.Boolean.annotate({ description: 'Response is a simple boolean' }),
  Schema.Record(Schema.String, Schema.Unknown).annotate({ description: 'Response is a simple object' })
]);

export const ComplexTypesDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.Struct({
    parameterObject: Schema.Struct({
      first: Schema.optionalKey(Schema.Struct({
        second: Schema.optionalKey(Schema.Struct({
          third: Schema.optionalKey(Schema.String)
        }))
      }))
    }).annotate({ description: 'Parameter containing object' }),
    parameterReference: Schema.Struct({
      prop: Schema.optionalKey(Schema.String.annotate({ description: 'This is a simple string property' }))
    }).annotate({ description: 'This is a model with one string property' })
  })
});

/**
 * Successful response
 */
export const ComplexTypesResponseSchema = Schema.Array(ModelWithStringSchema).annotate({ description: 'Successful response' });

export const CallWithResultFromHeaderDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const TestErrorCodeDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.Struct({
    status: Schema.String.annotate({ description: 'Status code to return' })
  })
});

export const NonAsciiæøåÆøÅöôêÊ字符串DataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.Struct({
    nonAsciiParamæøåÆØÅöôêÊ: Schema.Number.check(Schema.isInt()).annotate({ description: 'Dummy input param' })
  })
});

/**
 * Successful response
 */
export const NonAsciiæøåÆøÅöôêÊ字符串ResponseSchema = NonAsciiStringæøåÆøÅöôêÊ字符串Schema.annotate({ description: 'Successful response' });

export const PostApiVbyApiVersionBodyDataSchema = Schema.Struct({
  body: ParameterActivityParamsSchema.annotate({ description: 'Body should not be unknown' }),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * OK
 */
export const PostApiVbyApiVersionBodyResponseSchema = ResponsePostActivityResponseSchema.annotate({ description: 'OK' });
