// This file is auto-generated by @hey-api/openapi-ts

import * as Schema from 'effect/Schema';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import { CallToTestOrderOfParamsDataSchema, CallWithDefaultOptionalParametersDataSchema, CallWithDefaultParametersDataSchema, CallWithDescriptionsDataSchema, CallWithDuplicateResponsesDataSchema, CallWithDuplicateResponsesResponseSchema, CallWithNoContentResponseDataSchema, CallWithParametersDataSchema, CallWithResponseAndNoContentResponseDataSchema, CallWithResponseAndNoContentResponseResponseSchema, CallWithResponseDataSchema, CallWithResponseResponseSchema, CallWithResponsesDataSchema, CallWithResponsesResponseSchema, CallWithResultFromHeaderDataSchema, CallWithWeirdParameterNamesDataSchema, CollectionFormatDataSchema, ComplexTypesDataSchema, ComplexTypesResponseSchema, DeleteCallWithoutParametersAndResponseDataSchema, DummyADataSchema, DummyBDataSchema, DuplicateName2DataSchema, DuplicateName3DataSchema, DuplicateName4DataSchema, DuplicateNameDataSchema, FooWowDataSchema, GetCallWithoutParametersAndResponseDataSchema, HeadCallWithoutParametersAndResponseDataSchema, NonAsciiæøåÆøÅöôêÊ字符串DataSchema, NonAsciiæøåÆøÅöôêÊ字符串ResponseSchema, OptionsCallWithoutParametersAndResponseDataSchema, PatchApiVbyApiVersionNoTagDataSchema, PatchCallWithoutParametersAndResponseDataSchema, PostApiVbyApiVersionBodyDataSchema, PostApiVbyApiVersionBodyResponseSchema, PostCallWithoutParametersAndResponseDataSchema, PutCallWithoutParametersAndResponseDataSchema, ServiceWithEmptyTagDataSchema, TestErrorCodeDataSchema, TypesDataSchema, TypesResponseSchema } from './effect-schema.gen';
import type { CallToTestOrderOfParamsData, CallWithDefaultOptionalParametersData, CallWithDefaultParametersData, CallWithDescriptionsData, CallWithDuplicateResponsesData, CallWithDuplicateResponsesErrors, CallWithDuplicateResponsesResponses, CallWithNoContentResponseData, CallWithNoContentResponseResponses, CallWithParametersData, CallWithResponseAndNoContentResponseData, CallWithResponseAndNoContentResponseResponses, CallWithResponseData, CallWithResponseResponses, CallWithResponsesData, CallWithResponsesErrors, CallWithResponsesResponses, CallWithResultFromHeaderData, CallWithResultFromHeaderErrors, CallWithResultFromHeaderResponses, CallWithWeirdParameterNamesData, CollectionFormatData, ComplexTypesData, ComplexTypesErrors, ComplexTypesResponses, DeleteCallWithoutParametersAndResponseData, DummyAData, DummyAResponses, DummyBData, DummyBResponses, DuplicateName2Data, DuplicateName3Data, DuplicateName4Data, DuplicateNameData, FooWowData, FooWowResponses, GetCallWithoutParametersAndResponseData, HeadCallWithoutParametersAndResponseData, NonAsciiæøåÆøÅöôêÊ字符串Data, NonAsciiæøåÆøÅöôêÊ字符串Responses, OptionsCallWithoutParametersAndResponseData, PatchApiVbyApiVersionNoTagData, PatchApiVbyApiVersionNoTagResponses, PatchCallWithoutParametersAndResponseData, PostApiVbyApiVersionBodyData, PostApiVbyApiVersionBodyErrors, PostApiVbyApiVersionBodyResponses, PostCallWithoutParametersAndResponseData, PutCallWithoutParametersAndResponseData, ServiceWithEmptyTagData, TestErrorCodeData, TestErrorCodeErrors, TestErrorCodeResponses, TypesData, TypesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, TResponse = unknown> = Options2<TData, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const serviceWithEmptyTag = (options?: Options<ServiceWithEmptyTagData>): RequestResult<unknown, unknown> => (options?.client ?? client).get<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(ServiceWithEmptyTagDataSchema)(data),
  url: '/api/v{api-version}/no+tag',
  ...options
});

export const patchApiVbyApiVersionNoTag = (options?: Options<PatchApiVbyApiVersionNoTagData>): RequestResult<PatchApiVbyApiVersionNoTagResponses, unknown> => (options?.client ?? client).patch<PatchApiVbyApiVersionNoTagResponses, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(PatchApiVbyApiVersionNoTagDataSchema)(data),
  url: '/api/v{api-version}/no+tag',
  ...options
});

export const fooWow = (options?: Options<FooWowData>): RequestResult<FooWowResponses, unknown> => (options?.client ?? client).put<FooWowResponses, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(FooWowDataSchema)(data),
  url: '/api/v{api-version}/no+tag',
  ...options
});

export const deleteCallWithoutParametersAndResponse = (options?: Options<DeleteCallWithoutParametersAndResponseData>): RequestResult<unknown, unknown> => (options?.client ?? client).delete<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(DeleteCallWithoutParametersAndResponseDataSchema)(data),
  url: '/api/v{api-version}/simple',
  ...options
});

export const getCallWithoutParametersAndResponse = (options?: Options<GetCallWithoutParametersAndResponseData>): RequestResult<unknown, unknown> => (options?.client ?? client).get<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(GetCallWithoutParametersAndResponseDataSchema)(data),
  url: '/api/v{api-version}/simple',
  ...options
});

export const headCallWithoutParametersAndResponse = (options?: Options<HeadCallWithoutParametersAndResponseData>): RequestResult<unknown, unknown> => (options?.client ?? client).head<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(HeadCallWithoutParametersAndResponseDataSchema)(data),
  url: '/api/v{api-version}/simple',
  ...options
});

export const optionsCallWithoutParametersAndResponse = (options?: Options<OptionsCallWithoutParametersAndResponseData>): RequestResult<unknown, unknown> => (options?.client ?? client).options<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(OptionsCallWithoutParametersAndResponseDataSchema)(data),
  url: '/api/v{api-version}/simple',
  ...options
});

export const patchCallWithoutParametersAndResponse = (options?: Options<PatchCallWithoutParametersAndResponseData>): RequestResult<unknown, unknown> => (options?.client ?? client).patch<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(PatchCallWithoutParametersAndResponseDataSchema)(data),
  url: '/api/v{api-version}/simple',
  ...options
});

export const postCallWithoutParametersAndResponse = (options?: Options<PostCallWithoutParametersAndResponseData>): RequestResult<unknown, unknown> => (options?.client ?? client).post<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(PostCallWithoutParametersAndResponseDataSchema)(data),
  url: '/api/v{api-version}/simple',
  ...options
});

export const putCallWithoutParametersAndResponse = (options?: Options<PutCallWithoutParametersAndResponseData>): RequestResult<unknown, unknown> => (options?.client ?? client).put<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(PutCallWithoutParametersAndResponseDataSchema)(data),
  url: '/api/v{api-version}/simple',
  ...options
});

export const callWithDescriptions = (options?: Options<CallWithDescriptionsData>): RequestResult<unknown, unknown> => (options?.client ?? client).post<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(CallWithDescriptionsDataSchema)(data),
  url: '/api/v{api-version}/descriptions/',
  ...options
});

export const callWithParameters = (options: Options<CallWithParametersData>): RequestResult<unknown, unknown> => (options.client ?? client).post<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(CallWithParametersDataSchema)(data),
  url: '/api/v{api-version}/parameters/{parameterPath}',
  ...options
});

export const callWithWeirdParameterNames = (options: Options<CallWithWeirdParameterNamesData>): RequestResult<unknown, unknown> => (options.client ?? client).post<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(CallWithWeirdParameterNamesDataSchema)(data),
  url: '/api/v{api-version}/parameters/{parameter.path.1}/{parameter-path-2}/{PARAMETER-PATH-3}',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

export const callWithDefaultParameters = (options: Options<CallWithDefaultParametersData>): RequestResult<unknown, unknown> => (options.client ?? client).get<unknown, unknown>({
  querySerializer: { parameters: { parameterModel: { object: { explode: false, style: 'form' } } } },
  requestValidator: async (data) => Schema.decodeUnknownPromise(CallWithDefaultParametersDataSchema)(data),
  url: '/api/v{api-version}/defaults',
  ...options
});

export const callWithDefaultOptionalParameters = (options?: Options<CallWithDefaultOptionalParametersData>): RequestResult<unknown, unknown> => (options?.client ?? client).post<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(CallWithDefaultOptionalParametersDataSchema)(data),
  url: '/api/v{api-version}/defaults',
  ...options
});

export const callToTestOrderOfParams = (options: Options<CallToTestOrderOfParamsData>): RequestResult<unknown, unknown> => (options.client ?? client).put<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(CallToTestOrderOfParamsDataSchema)(data),
  url: '/api/v{api-version}/defaults',
  ...options
});

export const duplicateName = (options?: Options<DuplicateNameData>): RequestResult<unknown, unknown> => (options?.client ?? client).delete<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(DuplicateNameDataSchema)(data),
  url: '/api/v{api-version}/duplicate',
  ...options
});

export const duplicateName2 = (options?: Options<DuplicateName2Data>): RequestResult<unknown, unknown> => (options?.client ?? client).get<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(DuplicateName2DataSchema)(data),
  url: '/api/v{api-version}/duplicate',
  ...options
});

export const duplicateName3 = (options?: Options<DuplicateName3Data>): RequestResult<unknown, unknown> => (options?.client ?? client).post<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(DuplicateName3DataSchema)(data),
  url: '/api/v{api-version}/duplicate',
  ...options
});

export const duplicateName4 = (options?: Options<DuplicateName4Data>): RequestResult<unknown, unknown> => (options?.client ?? client).put<unknown, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(DuplicateName4DataSchema)(data),
  url: '/api/v{api-version}/duplicate',
  ...options
});

export const callWithNoContentResponse = (options?: Options<CallWithNoContentResponseData>): RequestResult<CallWithNoContentResponseResponses, unknown> => (options?.client ?? client).get<CallWithNoContentResponseResponses, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(CallWithNoContentResponseDataSchema)(data),
  url: '/api/v{api-version}/no-content',
  ...options
});

export const callWithResponseAndNoContentResponse = (options?: Options<CallWithResponseAndNoContentResponseData>): RequestResult<CallWithResponseAndNoContentResponseResponses, unknown> => (options?.client ?? client).get<CallWithResponseAndNoContentResponseResponses, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(CallWithResponseAndNoContentResponseDataSchema)(data),
  responseTransformer: async (data) => Schema.decodeUnknownPromise(CallWithResponseAndNoContentResponseResponseSchema)(data),
  url: '/api/v{api-version}/multiple-tags/response-and-no-content',
  ...options
});

export const dummyA = (options?: Options<DummyAData>): RequestResult<DummyAResponses, unknown> => (options?.client ?? client).get<DummyAResponses, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(DummyADataSchema)(data),
  url: '/api/v{api-version}/multiple-tags/a',
  ...options
});

export const dummyB = (options?: Options<DummyBData>): RequestResult<DummyBResponses, unknown> => (options?.client ?? client).get<DummyBResponses, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(DummyBDataSchema)(data),
  url: '/api/v{api-version}/multiple-tags/b',
  ...options
});

export const callWithResponse = (options?: Options<CallWithResponseData>): RequestResult<CallWithResponseResponses, unknown> => (options?.client ?? client).get<CallWithResponseResponses, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(CallWithResponseDataSchema)(data),
  responseTransformer: async (data) => Schema.decodeUnknownPromise(CallWithResponseResponseSchema)(data),
  url: '/api/v{api-version}/response',
  ...options
});

export const callWithDuplicateResponses = (options?: Options<CallWithDuplicateResponsesData>): RequestResult<CallWithDuplicateResponsesResponses, CallWithDuplicateResponsesErrors> => (options?.client ?? client).post<CallWithDuplicateResponsesResponses, CallWithDuplicateResponsesErrors>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(CallWithDuplicateResponsesDataSchema)(data),
  responseTransformer: async (data) => Schema.decodeUnknownPromise(CallWithDuplicateResponsesResponseSchema)(data),
  url: '/api/v{api-version}/response',
  ...options
});

export const callWithResponses = (options?: Options<CallWithResponsesData>): RequestResult<CallWithResponsesResponses, CallWithResponsesErrors> => (options?.client ?? client).put<CallWithResponsesResponses, CallWithResponsesErrors>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(CallWithResponsesDataSchema)(data),
  responseTransformer: async (data) => Schema.decodeUnknownPromise(CallWithResponsesResponseSchema)(data),
  url: '/api/v{api-version}/response',
  ...options
});

export const collectionFormat = (options: Options<CollectionFormatData>): RequestResult<unknown, unknown> => (options.client ?? client).get<unknown, unknown>({
  querySerializer: { parameters: {
      parameterArrayCSV: { array: { explode: false } },
      parameterArraySSV: { array: { explode: false } },
      parameterArrayTSV: { array: { explode: false } },
      parameterArrayPipes: { array: { explode: false } }
    } },
  requestValidator: async (data) => Schema.decodeUnknownPromise(CollectionFormatDataSchema)(data),
  url: '/api/v{api-version}/collectionFormat',
  ...options
});

export const types = (options: Options<TypesData>): RequestResult<TypesResponses, unknown> => (options.client ?? client).get<TypesResponses, unknown>({
  querySerializer: { parameters: { parameterArray: { array: { explode: false } }, parameterDictionary: { object: { explode: false, style: 'form' } } } },
  requestValidator: async (data) => Schema.decodeUnknownPromise(TypesDataSchema)(data),
  responseTransformer: async (data) => Schema.decodeUnknownPromise(TypesResponseSchema)(data),
  url: '/api/v{api-version}/types',
  ...options
});

export const complexTypes = (options: Options<ComplexTypesData>): RequestResult<ComplexTypesResponses, ComplexTypesErrors> => (options.client ?? client).get<ComplexTypesResponses, ComplexTypesErrors>({
  querySerializer: { parameters: { parameterObject: { object: { explode: false, style: 'form' } }, parameterReference: { object: { explode: false, style: 'form' } } } },
  requestValidator: async (data) => Schema.decodeUnknownPromise(ComplexTypesDataSchema)(data),
  responseTransformer: async (data) => Schema.decodeUnknownPromise(ComplexTypesResponseSchema)(data),
  url: '/api/v{api-version}/complex',
  ...options
});

export const callWithResultFromHeader = (options?: Options<CallWithResultFromHeaderData>): RequestResult<CallWithResultFromHeaderResponses, CallWithResultFromHeaderErrors> => (options?.client ?? client).post<CallWithResultFromHeaderResponses, CallWithResultFromHeaderErrors>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(CallWithResultFromHeaderDataSchema)(data),
  url: '/api/v{api-version}/header',
  ...options
});

export const testErrorCode = (options: Options<TestErrorCodeData>): RequestResult<TestErrorCodeResponses, TestErrorCodeErrors> => (options.client ?? client).post<TestErrorCodeResponses, TestErrorCodeErrors>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(TestErrorCodeDataSchema)(data),
  url: '/api/v{api-version}/error',
  ...options
});

export const nonAsciiæøåÆøÅöôêÊ字符串 = (options: Options<NonAsciiæøåÆøÅöôêÊ字符串Data>): RequestResult<NonAsciiæøåÆøÅöôêÊ字符串Responses, unknown> => (options.client ?? client).post<NonAsciiæøåÆøÅöôêÊ字符串Responses, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(NonAsciiæøåÆøÅöôêÊ字符串DataSchema)(data),
  responseTransformer: async (data) => Schema.decodeUnknownPromise(NonAsciiæøåÆøÅöôêÊ字符串ResponseSchema)(data),
  url: '/api/v{api-version}/non-ascii-æøåÆØÅöôêÊ字符串',
  ...options
});

/**
 * Body should not be unknown
 *
 * Body should not be unknown
 */
export const postApiVbyApiVersionBody = (options: Options<PostApiVbyApiVersionBodyData>): RequestResult<PostApiVbyApiVersionBodyResponses, PostApiVbyApiVersionBodyErrors> => (options.client ?? client).post<PostApiVbyApiVersionBodyResponses, PostApiVbyApiVersionBodyErrors>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(PostApiVbyApiVersionBodyDataSchema)(data),
  responseTransformer: async (data) => Schema.decodeUnknownPromise(PostApiVbyApiVersionBodyResponseSchema)(data),
  url: '/api/v{api-version}/body',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});
