// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { FooBarPostData, FooBarPostResponses, FooBarPutData, FooBarPutResponses, FooPostData, FooPostResponses, FooPutData, FooPutResponses, GetFooBarData, GetFooBarResponses, GetFooData, GetFooResponses } from './types.gen';
import { vFooBarPostResponse, vFooBarPutResponse, vFooPostResponse, vFooPutResponse, vGetFooBarResponse, vGetFooResponse } from './valibot.gen';

export type Options<TData extends TDataShape = TDataShape, TResponse = unknown> = Options2<TData, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getFoo = (options?: Options<GetFooData>): RequestResult<GetFooResponses, unknown> => (options?.client ?? client).get<GetFooResponses, unknown>({
  requestValidator: async (data) => await v.parseAsync(v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
  }), data),
  responseTransformer: async (data) => await v.parseAsync(vGetFooResponse, data),
  url: '/foo',
  ...options
});

export const fooPost = (options?: Options<FooPostData>): RequestResult<FooPostResponses, unknown> => (options?.client ?? client).post<FooPostResponses, unknown>({
  requestValidator: async (data) => await v.parseAsync(v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
  }), data),
  responseTransformer: async (data) => await v.parseAsync(vFooPostResponse, data),
  url: '/foo',
  ...options
});

export const fooPut = (options?: Options<FooPutData>): RequestResult<FooPutResponses, unknown> => (options?.client ?? client).put<FooPutResponses, unknown>({
  requestValidator: async (data) => await v.parseAsync(v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
  }), data),
  responseTransformer: async (data) => await v.parseAsync(vFooPutResponse, data),
  url: '/foo',
  ...options
});

export const getFooBar = (options?: Options<GetFooBarData>): RequestResult<GetFooBarResponses, unknown> => (options?.client ?? client).get<GetFooBarResponses, unknown>({
  requestValidator: async (data) => await v.parseAsync(v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
  }), data),
  responseTransformer: async (data) => await v.parseAsync(vGetFooBarResponse, data),
  url: '/foo/bar',
  ...options
});

export const fooBarPost = (options?: Options<FooBarPostData>): RequestResult<FooBarPostResponses, unknown> => (options?.client ?? client).post<FooBarPostResponses, unknown>({
  requestValidator: async (data) => await v.parseAsync(v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
  }), data),
  responseTransformer: async (data) => await v.parseAsync(vFooBarPostResponse, data),
  url: '/foo/bar',
  ...options
});

export const fooBarPut = (options?: Options<FooBarPutData>): RequestResult<FooBarPutResponses, unknown> => (options?.client ?? client).put<FooBarPutResponses, unknown>({
  requestValidator: async (data) => await v.parseAsync(v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
  }), data),
  responseTransformer: async (data) => await v.parseAsync(vFooBarPutResponse, data),
  url: '/foo/bar',
  ...options
});
