// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

/**
 * OK
 */
export const vGetFooResponse = v.string();

/**
 * OK
 */
export const vFooPostResponse = v.string();

/**
 * OK
 */
export const vFooPutResponse = v.string();

/**
 * OK
 */
export const vGetFooBarResponse = v.string();

/**
 * OK
 */
export const vFooBarPostResponse = v.string();

/**
 * OK
 */
export const vFooBarPutResponse = v.string();
