// This file is auto-generated by @hey-api/openapi-ts

import type * as Effect from 'effect/Effect';
import { HttpClient } from 'effect/unstable/http';
import { HttpApi, HttpApiClient, HttpApiEndpoint, HttpApiGroup, HttpApiSchema } from 'effect/unstable/httpapi';

import { CallToTestOrderOfParamsQuerySchema, CallWithDefaultOptionalParametersQuerySchema, CallWithDefaultParametersQuerySchema, CallWithDescriptionsQuerySchema, CallWithDuplicateResponsesResponse201Schema, CallWithDuplicateResponsesResponse202Schema, CallWithDuplicateResponsesResponse500Schema, CallWithDuplicateResponsesResponse501Schema, CallWithDuplicateResponsesResponse502Schema, CallWithParametersHeadersSchema, CallWithParametersPathParamsSchema, CallWithParametersQuerySchema, CallWithResponseAndNoContentResponseResponse200Schema, CallWithResponsesResponse200Schema, CallWithResponsesResponse201Schema, CallWithResponsesResponse202Schema, CallWithResponsesResponse500Schema, CallWithResponsesResponse501Schema, CallWithResponsesResponse502Schema, CallWithResultFromHeaderResponse200Schema, CallWithResultFromHeaderResponse400Schema, CallWithResultFromHeaderResponse500Schema, CallWithWeirdParameterNamesHeadersSchema, CallWithWeirdParameterNamesPathParamsSchema, CallWithWeirdParameterNamesPayloadSchema, CallWithWeirdParameterNamesQuerySchema, CollectionFormatQuerySchema, ComplexTypesQuerySchema, ComplexTypesResponse200Schema, ComplexTypesResponse400Schema, ComplexTypesResponse500Schema, NonAsciiæøåÆøÅöôêÊ字符串QuerySchema, NonAsciiæøåÆøÅöôêÊ字符串Response200Schema, PostApiVbyApiVersionBodyPayloadSchema, PostApiVbyApiVersionBodyResponse200Schema, PostApiVbyApiVersionBodyResponse400Schema, PostApiVbyApiVersionBodyResponse500Schema, TestErrorCodeQuerySchema, TestErrorCodeResponse200Schema, TestErrorCodeResponse500Schema, TestErrorCodeResponse501Schema, TestErrorCodeResponse502Schema, TestErrorCodeResponse503Schema, TypesPathParamsSchema, TypesQuerySchema, TypesResponse200Schema, TypesResponse201Schema, TypesResponse202Schema, TypesResponse203Schema } from './effect-schema.gen';

const DefaultGroup = HttpApiGroup.make('default').add(HttpApiEndpoint.get('serviceWithEmptyTag', '/api/v:api_version/no+tag'), HttpApiEndpoint.patch('patchApiVbyApiVersionNoTag', '/api/v:api_version/no+tag'), HttpApiEndpoint.put('fooWow', '/api/v:api_version/no+tag'), HttpApiEndpoint.post('postApiVbyApiVersionBody', '/api/v:api_version/body', {
  payload: PostApiVbyApiVersionBodyPayloadSchema,
  success: PostApiVbyApiVersionBodyResponse200Schema.pipe(HttpApiSchema.status(200)),
  error: [PostApiVbyApiVersionBodyResponse400Schema.pipe(HttpApiSchema.status(400)), PostApiVbyApiVersionBodyResponse500Schema.pipe(HttpApiSchema.status(500))]
}));

const SimpleGroup = HttpApiGroup.make('Simple').add(HttpApiEndpoint.delete('deleteCallWithoutParametersAndResponse', '/api/v:api_version/simple'), HttpApiEndpoint.get('getCallWithoutParametersAndResponse', '/api/v:api_version/simple'), HttpApiEndpoint.head('headCallWithoutParametersAndResponse', '/api/v:api_version/simple'), HttpApiEndpoint.options('optionsCallWithoutParametersAndResponse', '/api/v:api_version/simple'), HttpApiEndpoint.patch('patchCallWithoutParametersAndResponse', '/api/v:api_version/simple'), HttpApiEndpoint.post('postCallWithoutParametersAndResponse', '/api/v:api_version/simple'), HttpApiEndpoint.put('putCallWithoutParametersAndResponse', '/api/v:api_version/simple'));

const DescriptionsGroup = HttpApiGroup.make('Descriptions').add(HttpApiEndpoint.post('callWithDescriptions', '/api/v:api_version/descriptions/', {
  query: CallWithDescriptionsQuerySchema
}));

const ParametersGroup = HttpApiGroup.make('Parameters').add(HttpApiEndpoint.post('callWithParameters', '/api/v:api_version/parameters/:parameterPath', {
  params: CallWithParametersPathParamsSchema,
  query: CallWithParametersQuerySchema,
  headers: CallWithParametersHeadersSchema
}), HttpApiEndpoint.post('callWithWeirdParameterNames', '/api/v:api_version/parameters/:parameter_path_1/:parameter_path_2/:PARAMETER_PATH_3', {
  params: CallWithWeirdParameterNamesPathParamsSchema,
  query: CallWithWeirdParameterNamesQuerySchema,
  headers: CallWithWeirdParameterNamesHeadersSchema,
  payload: CallWithWeirdParameterNamesPayloadSchema
}));

const DefaultsGroup = HttpApiGroup.make('Defaults').add(HttpApiEndpoint.get('callWithDefaultParameters', '/api/v:api_version/defaults', {
  query: CallWithDefaultParametersQuerySchema
}), HttpApiEndpoint.post('callWithDefaultOptionalParameters', '/api/v:api_version/defaults', {
  query: CallWithDefaultOptionalParametersQuerySchema
}), HttpApiEndpoint.put('callToTestOrderOfParams', '/api/v:api_version/defaults', {
  query: CallToTestOrderOfParamsQuerySchema
}));

const DuplicateGroup = HttpApiGroup.make('Duplicate').add(HttpApiEndpoint.delete('duplicateName', '/api/v:api_version/duplicate'), HttpApiEndpoint.get('duplicateName2', '/api/v:api_version/duplicate'), HttpApiEndpoint.post('duplicateName3', '/api/v:api_version/duplicate'), HttpApiEndpoint.put('duplicateName4', '/api/v:api_version/duplicate'));

const NoContentGroup = HttpApiGroup.make('NoContent').add(HttpApiEndpoint.get('callWithNoContentResponse', '/api/v:api_version/no-content', {
  success: HttpApiSchema.Empty(204)
}));

const ResponseGroup = HttpApiGroup.make('Response').add(HttpApiEndpoint.get('callWithResponseAndNoContentResponse', '/api/v:api_version/multiple-tags/response-and-no-content', {
  success: [CallWithResponseAndNoContentResponseResponse200Schema.pipe(HttpApiSchema.status(200)), HttpApiSchema.Empty(204)]
}), HttpApiEndpoint.get('callWithResponse', '/api/v:api_version/response'), HttpApiEndpoint.post('callWithDuplicateResponses', '/api/v:api_version/response', {
  success: [CallWithDuplicateResponsesResponse201Schema.pipe(HttpApiSchema.status(201)), CallWithDuplicateResponsesResponse202Schema.pipe(HttpApiSchema.status(202))],
  error: [
    CallWithDuplicateResponsesResponse500Schema.pipe(HttpApiSchema.status(500)),
    CallWithDuplicateResponsesResponse501Schema.pipe(HttpApiSchema.status(501)),
    CallWithDuplicateResponsesResponse502Schema.pipe(HttpApiSchema.status(502))
  ]
}), HttpApiEndpoint.put('callWithResponses', '/api/v:api_version/response', {
  success: [
    CallWithResponsesResponse200Schema.pipe(HttpApiSchema.status(200)),
    CallWithResponsesResponse201Schema.pipe(HttpApiSchema.status(201)),
    CallWithResponsesResponse202Schema.pipe(HttpApiSchema.status(202))
  ],
  error: [
    CallWithResponsesResponse500Schema.pipe(HttpApiSchema.status(500)),
    CallWithResponsesResponse501Schema.pipe(HttpApiSchema.status(501)),
    CallWithResponsesResponse502Schema.pipe(HttpApiSchema.status(502))
  ]
}));

const MultipleTags1Group = HttpApiGroup.make('MultipleTags1').add(HttpApiEndpoint.get('dummyA', '/api/v:api_version/multiple-tags/a', {
  success: HttpApiSchema.Empty(204)
}), HttpApiEndpoint.get('dummyB', '/api/v:api_version/multiple-tags/b', {
  success: HttpApiSchema.Empty(204)
}));

const CollectionFormatGroup = HttpApiGroup.make('CollectionFormat').add(HttpApiEndpoint.get('collectionFormat', '/api/v:api_version/collectionFormat', {
  query: CollectionFormatQuerySchema
}));

const TypesGroup = HttpApiGroup.make('Types').add(HttpApiEndpoint.get('types', '/api/v:api_version/types', {
  params: TypesPathParamsSchema,
  query: TypesQuerySchema,
  success: [
    TypesResponse200Schema.pipe(HttpApiSchema.status(200)),
    TypesResponse201Schema.pipe(HttpApiSchema.status(201)),
    TypesResponse202Schema.pipe(HttpApiSchema.status(202)),
    TypesResponse203Schema.pipe(HttpApiSchema.status(203))
  ]
}));

const ComplexGroup = HttpApiGroup.make('Complex').add(HttpApiEndpoint.get('complexTypes', '/api/v:api_version/complex', {
  query: ComplexTypesQuerySchema,
  success: ComplexTypesResponse200Schema.pipe(HttpApiSchema.status(200)),
  error: [ComplexTypesResponse400Schema.pipe(HttpApiSchema.status(400)), ComplexTypesResponse500Schema.pipe(HttpApiSchema.status(500))]
}));

const HeaderGroup = HttpApiGroup.make('Header').add(HttpApiEndpoint.post('callWithResultFromHeader', '/api/v:api_version/header', {
  success: CallWithResultFromHeaderResponse200Schema.pipe(HttpApiSchema.status(200)),
  error: [CallWithResultFromHeaderResponse400Schema.pipe(HttpApiSchema.status(400)), CallWithResultFromHeaderResponse500Schema.pipe(HttpApiSchema.status(500))]
}));

const ErrorGroup = HttpApiGroup.make('Error').add(HttpApiEndpoint.post('testErrorCode', '/api/v:api_version/error', {
  query: TestErrorCodeQuerySchema,
  success: TestErrorCodeResponse200Schema.pipe(HttpApiSchema.status(200)),
  error: [
    TestErrorCodeResponse500Schema.pipe(HttpApiSchema.status(500)),
    TestErrorCodeResponse501Schema.pipe(HttpApiSchema.status(501)),
    TestErrorCodeResponse502Schema.pipe(HttpApiSchema.status(502)),
    TestErrorCodeResponse503Schema.pipe(HttpApiSchema.status(503))
  ]
}));

const NonAsciiÆøåÆøÅöôêÊGroup = HttpApiGroup.make('nonAsciiÆøåÆøÅöôêÊ').add(HttpApiEndpoint.post('nonAsciiæøåÆøÅöôêÊ字符串', '/api/v:api_version/non-ascii-æøåÆØÅöôêÊ字符串', {
  query: NonAsciiæøåÆøÅöôêÊ字符串QuerySchema,
  success: NonAsciiæøåÆøÅöôêÊ字符串Response200Schema.pipe(HttpApiSchema.status(200))
}));

export const Api = HttpApi.make('Api').add(DefaultGroup, SimpleGroup, DescriptionsGroup, ParametersGroup, DefaultsGroup, DuplicateGroup, NoContentGroup, ResponseGroup, MultipleTags1Group, CollectionFormatGroup, TypesGroup, ComplexGroup, HeaderGroup, ErrorGroup, NonAsciiÆøåÆøÅöôêÊGroup);

export function makeClient(options?: {
  readonly baseUrl?: URL | string | undefined;
  readonly transformClient?: ((client: HttpClient.HttpClient) => HttpClient.HttpClient) | undefined;
  readonly transformResponse?: ((effect: Effect.Effect<unknown, unknown, unknown>) => Effect.Effect<unknown, unknown, unknown>) | undefined;
}) {
  return HttpApiClient.make(Api, options);
}
