// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * OK
 */
export const zGetFooResponse = z.string();

/**
 * OK
 */
export const zFooPostResponse = z.string();

/**
 * OK
 */
export const zFooPutResponse = z.string();

/**
 * OK
 */
export const zGetFooBarResponse = z.string();

/**
 * OK
 */
export const zFooBarPostResponse = z.string();

/**
 * OK
 */
export const zFooBarPutResponse = z.string();
